### ISSUE TITLE
Alcinoe font for IOS 13 sdk

### ISSUE THREAD

**Issue by KadriKaya** [MagicFoundation/Alcinoe#101]
Hi guys,
https://quality.embarcadero.com/browse/rsp-26388
in this link there is a problem that the system fonts for IOS 13 are problematic and look like "Times New Roman". Currently, the standard FMX label does not contain such a problem, but Alcinoe still has this problem. Should we wait for an update for this or is there anyone writing a piece of code that works for you? Because Apple obliges 13 SDKs after April 2020 and frankly it is a problem for my project containing this alcinoe.

Note: IOS 12 sdk also this problem.
Please accept my apologies for Google translation

Thanks everyone.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
