### ISSUE TITLE
ALText html features and True font

### ISSUE THREAD

**Issue by gatscross** [MagicFoundation/Alcinoe#107]
I like the ALText component that supports html, but I have a problem how to implement html break lines with </br> or it doesn't work.
then the next thing how to make the fontstyle follow the font used at design time, I followed the reference on youtube to make modifications to the FMX.FontGlyphs.Android.pas file. I tried making it using the TText component successfully, but with ALText it didn't work. [The following is the sample repository link that I created](https://github.com/aam4gian/news_app) 

![image](https://user-images.githubusercontent.com/62690731/78102213-fad9cd80-7413-11ea-8591-6ef30b131e36.png)

**Comment by Zeus64** [comment]
Just one question, with the normal system font (so without patching the FMX.FontGlyphs.Android.pas) does it's work as expected ? as far as I see the break line work in your sample, but it's look like you want 2 break lines to have space between paragraph, so try to replace your #13#10 by #13#10#13#10 (so add 2 breaklines instead of one)

**Comment by aam4gian** [comment]
without using a patch file the case is still the same. for break lines I've tried it by adding #13#10#13#10 but it will only be text #13#10#13#10 which is also displayed. what you see in the picture above is because ALText in WordWrap mode enables and follows the screen dimensions.

**Comment by aam4gian** [comment]
this is look rotate screen

![image](https://user-images.githubusercontent.com/62690731/78115564-2fa64e80-742d-11ea-9800-08757af4dbe6.png)

**Comment by Zeus64** [comment]
@aam4gian you are on ios or android ? is it the case in all platform? Can you try to replace the #13#10 by <br> ?

**Comment by aam4gian** [comment]
I only tried it on an Android device. just using <br> it also doesn't have any effect, but it still has the same problem.

**Comment by Zeus64** [comment]
can you try on windows ?

**Comment by aam4gian** [comment]
I've tried it on windows, it still doesn't work
[altext.zip](https://github.com/Zeus64/alcinoe/files/4425996/altext.zip)

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
