### ISSUE TITLE
ALLiveVideoChatClient  Android crashed 

### ISSUE THREAD

**Issue by Mbear07** [MagicFoundation/Alcinoe#109]
Hi there,
After a fight :-) I could build the  ALLiveVideoChatClient with android and tried to run on my device but before I can catch the Formcreate event the application just crashes..
From the Android Device Monitor I have got a log:
": I/VideoChatClien(25191): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.view.OnApplyWindowInsetsListener" on path: DexPathList[[zip file "/data/app/com.embarcadero.ALLiveVideoChatClient-HG1hUBp9hXDWXPGu5g5XrA==/base.apk"],nativeLibraryDirectories=[/data/app/com.embarcadero.ALLiveVideoChatClient-HG1hUBp9hXDWXPGu5g5XrA==/lib/arm, /data/app/com.embarcadero.ALLiveVideoChatClient-HG1hUBp9hXDWXPGu5g5XrA==/base.apk!/lib/armeabi-v7a, /system/lib]]"

When I tried to enable the android-support-v4.dex.jar at the project then I had an error
"... dx.bat ... exited with code 1." 
(I've already used your dx.bat file)
Any suggestions what I have to check? 
/Delphi Rio 10.3.3, Latest version of alcione (device: Samsung A20 Android 9) 
32 or 64 bit same result/

**Comment by Zeus64** [comment]
I will try to make a clear doc how to install webrtc this week end. you do not need to enable the android-support-v4.dex.jar, disable it, but use instead the jars located in \lib\jars\

**Comment by Mbear07** [comment]
Hi Zeus64,

Thank you for your answer.
Just to be clear:
I did download your whole project and I did what was in "Install Alcinoe" part.
(set paths(patche and originals), + replace dx bat )
If I open ALLiveVideoChatClient project I can see under the libraries that the project uses your jar files from  \lib\jars\; (3  jars file: webrtc, alcione-webrtc, support-annotations)

regards,
Tamas

**Comment by Zeus64** [comment]
@Mbear07 when you have the line ... dx.bat ... exited with code 1 can you copy it and launch it in the cmd.exe to see the full error message ?

**Comment by Mbear07** [comment]
Yes, but It happened when I enabled the android-support-v4.dex.jar :

This is the error from the command window:
"Error: Program type already present: android.support.annotation.AnimRes
Compilation failed"

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
