### ISSUE TITLE
10.3.3: can't deploy ALLiveVideoChatClient with files

### ISSUE THREAD

**Issue by kazuser** [MagicFoundation/Alcinoe#112]
Hi!

**### My setup is**:
![изображение](https://user-images.githubusercontent.com/3335273/78892699-aa094b00-7a8b-11ea-94e9-729773bc6a05.png)

![изображение](https://user-images.githubusercontent.com/3335273/78893366-10429d80-7a8d-11ea-97d9-864bee62d6ee.png)

![изображение](https://user-images.githubusercontent.com/3335273/78893741-a70f5a00-7a8d-11ea-92db-ea3c61e9a877.png)

![0](https://user-images.githubusercontent.com/3335273/78893504-44b65980-7a8d-11ea-9411-d374b5e3bcfc.gif)

_______________________________________________________________________________________

**### My problem is**: I can't deploy **ALLiveVideoChatClient** for iOS with files **Info.plist** and **WebRTC**:

![0](https://user-images.githubusercontent.com/3335273/78897030-5864be80-7a93-11ea-9871-23f696f6d15b.gif)

![изображение](https://user-images.githubusercontent.com/3335273/78897156-8f3ad480-7a93-11ea-8b4e-36d877f8f152.png)

But if files are deleted from project then deploy is ok but app is empty (black screen only) :(

![1](https://user-images.githubusercontent.com/3335273/78897175-9530b580-7a93-11ea-81f8-98d6ba7a2b77.gif)

**Comment by Zeus64** [comment]
hi kazuser, i will make a clear doc about webrtc soon
in the meantime, did you follow the readme.txt located in Alcinoe\lib\ios\webrtc :

> The framework must be signed with the same team identifier in the main executable code signature.
> The team identifier is the 10-character alphanumeric string, such as YH9SZ5LKR4, associated with your developer account, 
> and recorded in your Apple-issued signing certificate.
> 
> You must do this manually still embarcadero implement it
> https://quality.embarcadero.com/browse/RSP-22899
> 
> codesign -s <Identity> /YourPathto/WebRTC.framework/WebRTC
> 
> After you need to deploy yourself the WebRTC.framework in the .\Frameworks\WebRTC.framework
> file to deploy: 
>   Info.plist
>   LICENSE.md
>   WebRTC
>   _CodeSignature\CodeResources
>   
>   
> Stripping Unwanted Architectures From WebRTC
> http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/
> 
> lipo -info /YourPathto/WebRTC.framework/WebRTC
> lipo -remove i386 /YourPathto/WebRTC.framework/WebRTC -o /YourPathto/WebRTC.framework/WebRTC 
> lipo -remove x86_64 /YourPathto/WebRTC.framework/WebRTC -o /YourPathto/WebRTC.framework/WebRTC
> lipo -info /YourPathto/WebRTC.framework/WebRTC

**Comment by kazuser** [comment]
Yep, of course.
Step by step.




Here is another: when I changing "**.\Frameworks\WebRTC.framework**" to "**.\**" (in Project > Deployment) — no any "**e80000c5**", app deploys successfully but it's still empty (black screen) 🤔

**Comment by kazuser** [comment]
And here is my version of WebRTC-file after "codesign":

![изображение](https://user-images.githubusercontent.com/3335273/78916992-16964100-7ab0-11ea-8e9b-10122844e919.png)

**Comment by kazuser** [comment]
With updated (and signed before deploy) version [GoogleWebRTC-1.1.29400](https://dl.google.com/dl/cpdc/f310fce01248f022/GoogleWebRTC-1.1.29400.tar.gz) the same :(

**Comment by kazuser** [comment]
Could you please test/confirm this?

**1** Create a brand new FMX-project
**2** Select "iOS Device 64-bit" and fill "CFBundleIdentifier"
**3** Create a new text-file somewhere
**4** Open Project > Deployment and attach that text-file 
**5** Set ".\Frameworks\WebRTC.framework" in Project > Deployment > Remote Path
**6** Deploy

**Comment by kazuser** [comment]
![изображение](https://user-images.githubusercontent.com/3335273/78921762-3aa95080-7ab7-11ea-8471-a57671b4a415.png)


+


![изображение](https://user-images.githubusercontent.com/3335273/78921777-41d05e80-7ab7-11ea-9896-1643cdba36d1.png)



What do you think about it?

**Comment by kazuser** [comment]
[Was in GIF above](https://user-images.githubusercontent.com/3335273/78897030-5864be80-7a93-11ea-9871-23f696f6d15b.gif):
![изображение](https://user-images.githubusercontent.com/3335273/78922161-e6eb3700-7ab7-11ea-83df-7542c6521244.png)



[Became in last picture below](https://user-images.githubusercontent.com/3335273/78921936-878d2700-7ab7-11ea-99c1-b18969ff12c9.png):
![изображение](https://user-images.githubusercontent.com/3335273/78922219-fff3e800-7ab7-11ea-9086-6c1bb7278ee7.png)


Yeah I see the difference but anyway the error still present :/

**Comment by kazuser** [comment]
> 
> 
> hi kazuser, i will make a clear doc about webrtc soon
> in the meantime, did you follow the readme.txt located in Alcinoe\lib\ios\webrtc :
> 
.....
> > After you need to deploy yourself the WebRTC.framework in the .\Frameworks\WebRTC.framework
> > file to deploy:
> > Info.plist
> > LICENSE.md
> > WebRTC
> > _CodeSignature\CodeResources
.....


BTW where I can get "_CodeSignature\CodeResources"? There is no any "_CodeSignature\CodeResources" in your library :-/

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.

**Comment by kazuser** [comment]
Thank you.

I already forgot why I wanted to use it.

But better late than never, of course 😁
