### ISSUE TITLE
ALVideoPlayer and ALFmxControls Issue

### ISSUE THREAD

**Issue by jptec30** [MagicFoundation/Alcinoe#120]
Hi,

I created a new project and added the patched path and orginal path. I can compile successfully in android 32 bit delphi 10.3.3 but I cant run . After loading then quit automatically, please advise how to solve. 
for the alfmxcontrols sample project, when open it I show this error.

![20200420112132](https://user-images.githubusercontent.com/10337279/79711619-e3974d00-82fa-11ea-989f-f0a90bf72371.png)

when I try to compile , it show below. Please advise how to solve it
![20200420113533](https://user-images.githubusercontent.com/10337279/79711696-1d685380-82fb-11ea-8e75-dbbfab91850f.png)

**Comment by Zeus64** [comment]
@jptec30 hmm this is quite bad, with version of delphi do you use ?

**Comment by jptec30** [comment]
delphi 10.3.3 , android SDK 26.2 32 bit.

any advise ?

**Comment by Zeus64** [comment]
something definitively go wrong ;( did you install some "tools" in your delphi? I never saw this error. Can you try to uninstall the bpl, open the alfmxcontrols but not the main unit, and launch it ? also with BPL did you install in your delphi? the bpl located in https://github.com/Zeus64/alcinoe/tree/master/lib/bpl/alcinoe/Win32/rio ?

**Comment by jptec30** [comment]
yes, I installed bpl as you stated dated 13 april. if I remove bpl and open the alfmxcontrols not the main unit, it will prompt no component and ask for action no any address violation.
Also I did not install tools, Just install component.  


Actually I create a new project and just put ALVideoPlayerSurface , at design time all is ok. however, when deploy to android. it show loading and then quit without . when debug the project to show : Java class JdefaultBandwidthMeter could not be found"
you can download my sample and see what I m missing
[https://drive.google.com/open?id=1TUnmIpnBfkErHTr0u2ZAgX_M-3sGKA3K](url)

if you free , we can date a time to team viewer to check.

**Comment by Zeus64** [comment]
Did you include in your new project all the necessary jars located in https://github.com/Zeus64/alcinoe/tree/master/lib/jar/com.google.android.exoplayer ?

**Comment by jptec30** [comment]
sorry for late reply, I tested it is ok when included for new project. For the default project case cant open any idea?

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
