### ISSUE TITLE
Error on FMX.Menus

### ISSUE THREAD

**Issue by panmilkos** [MagicFoundation/Alcinoe#134]
I have this error since I upgrade the pack. My IDE 10.3.3
[DCC Fatal Error] FMX.Menus.pas(503): F2084 Internal Error: AV090B4F45(08FF0000)-R414B5654-0
I uninstall it and reinstall it but nothing.
I have this little code on Android32. On windows32 everything is ok (about the error). 

procedure TForm9.Button1Click(Sender: TObject);
begin
  ALVideoPlayerSurface1.VideoPlayer.prepare('http://1589348434446d4-sd.mp4', False);
end;

procedure TForm9.Button2Click(Sender: TObject);
begin
  ALVideoPlayerSurface1.VideoPlayer.prepare('http://1589348434446d4-sd.mp4', True);
end;

procedure TForm9.Button3Click(Sender: TObject);
begin
  if ALVideoPlayerSurface1.VideoPlayer.State = 2 then
  ALVideoPlayerSurface1.VideoPlayer.Start
  else
  if ALVideoPlayerSurface1.VideoPlayer.State = 4 then
  ALVideoPlayerSurface1.VideoPlayer.Start;
end;

procedure TForm9.Button4Click(Sender: TObject);
begin
  if ALVideoPlayerSurface1.VideoPlayer.State = 3 then
  ALVideoPlayerSurface1.VideoPlayer.pause;
end;

procedure TForm9.Button5Click(Sender: TObject);
begin
  ALVideoPlayerSurface1.resetVideoPlayer;
end;

procedure TForm9.Timer1Timer(Sender: TObject);
begin
  Label1.Text := IntToStr(ALVideoPlayerSurface1.VideoPlayer.State);
end;

**Comment by panmilkos** [comment]
Sorry... the problem has solved when i copy your Search path to my program.

**Comment by panmilkos** [comment]
I have this screen on this program.
https://mega.nz/file/gUdBwaoQ#8eJGNx3_MeXS8-Z9mXAiIYPqgmeTIcpJsiOdsVtaWfw
this still screen (no image) with sound.
You know what it is?

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
