### ISSUE TITLE
Portrait video recorded on the device is rotated in ExoPlayer

### ISSUE THREAD

**Issue by ilia-mandev** [MagicFoundation/Alcinoe#136]
Hi again!

This is probably OS/ExoPlayer issue, but if there is a fix (even a dirty/temporary fix) - please let us know. 

Even how to clear the movie rotation meta data?

When video is recorded in landscape mode, it plays as expected in both landscape and portrait device position.
The problem is when video is recorded in portrait mode - it's rotated 90 degrees while playing in both device positions.

Best regards,
Ilia.

**Comment by Zeus64** [comment]
Hello, please make a try with the last version of exoplayer. Everything seen be have been fixed in the latest committed version.
