### ISSUE TITLE
Displaying text in windows with ClearType

### ISSUE THREAD

**Issue by cboittin** [MagicFoundation/Alcinoe#137]
Hi,

I'm having issues with the text display on Windows 10 with GlobalUseDirect2D disabled and GlobalUseGDIPlusClearType enabled. I haven't tested on other versions of windows, but the issue persists in compatibility mode for xp or win7. Here is a screenshot which shows the problem :
![image](https://user-images.githubusercontent.com/4146349/86596467-8a09fa80-bf9a-11ea-9d85-bd54ec9c9065.png)

Each of these TALTexts have different settings, but should be displayed identically.
The first one has doubleBuffered to True and default Fill settings (default color, Kind set to None)
The second one has doubleBuffered to True, Fill Kind to Solid and Fill color set to Null (fully transparent)
The third one has doubleBuffered set to False and default Fill settings
The fourth one has doubleBuffered set to True, Fill Kind to None and Fill color set to Null, but resets to default Fill color when restarting the IDE
The last one has doubleBuffered set to True, Fill Kind to Solid and Fill color to #FF5084A1

Only the third one and last one display correctly (no double buffering, or forcing the background color).
At design time, they all display correctly.

Setting the form Quality to either HighPerformance or HighQuality doesn't help, although HighPerformance causes similar issues with TALEdit (shows a slight border sometimes even though the edit and its surroundings are the same color).

Any clue how i could solve this while keeping the double buffering and avoiding having to set a background color to all my TALTexts ?

**Comment by viniciusfbb** [comment]
The windows ClearType work only with backgrounds. The alforithm of the cleartype need to know the font color and the background color to calculate the color and intensity of the subpixels of contrast, that do not occur on other OS, only on Windows. 

When you have the DoubleBuffered true, the text will be draw in a empty (transparent) Bitmap/Texture that is inside of the control, which will store it for rendering in OnPaint without having to do all the drawing operations. But when you draw the text in a transparent background (background of the bitmap of doublebuffered) the ClearType will not work correctly.


Options to work:

1) Just set the DoubleBuffered False in Windows (the draw of the text will not be in a transparent bitmap of the doublebuffered, now it will draw direct in the window which is obviously not transparent, then the ClearType will work fine)

2) Set the background of the text always in Windows (the draw of the text will not be in a transparent bitmap of the doublebuffered, but in a opaque image)

3) Remove the ClearType and set Antialiased (the result will not be the best, the text will have a little blurry, but not need to have background and can use DoubleBuffered)

**Comment by Zeus64** [comment]
And now with Athens you have skia that handle better the font :) I close this issue and suggest to try Athens + Skia + Alcinoe
