### ISSUE TITLE
Android64 support?

### ISSUE THREAD

**Issue by Intelli-Forge** [MagicFoundation/Alcinoe#152]
Can't get an app working if it's built for Android64, Is it supported?

LogCat tells:
10-14 15:49:30.128: I/ActivityManager(1083): Start proc 20876:com.embarcadero.TabbedwithNavigation/u0a90 for activity com.embarcadero.TabbedwithNavigation/com.embarcadero.firemonkey.FMXNativeActivity
10-14 15:49:30.680: I/art(20876): Background sticky concurrent mark sweep GC freed 6570(317KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 7MB/7MB, paused 587us total 149.048ms
**10-14 15:49:30.690: W/linker(20876): /data/app/com.embarcadero.TabbedwithNavigation-2/lib/arm64/libTabbedwithNavigation.so: unused DT entry: type 0xf arg 0xec35**
10-14 15:49:30.939: I/art(20876): Background partial concurrent mark sweep GC freed 221(36KB) AllocSpace objects, 0(0B) LOS objects, 34% free, 7MB/11MB, paused 420us total 225.150ms
10-14 15:49:32.418: W/Icing(2009): Usage reports not received in time.
10-14 15:49:32.427: W/art(2009): Long monitor contention with owner highpool[11] (3559) at boolean rct.a(rcs, android.content.ServiceConnection, java.lang.String)(:com.google.android.gms@16089019@16.0.89 (040400-239467275):7) waiters=0 in void rcu.onServiceConnected(android.content.ComponentName, android.os.IBinder) for 2.365s
10-14 15:49:32.448: I/Zygote(893): Process 20876 exited cleanly (217)
10-14 15:49:32.450: I/ActivityManager(1083): Process com.embarcadero.TabbedwithNavigation (pid 20876) has died

It's an auto-generated simple TabbedwithNavigation project with ALFmxObjects in **uses** clause.

**Comment by LeeHyunChul777** [comment]
I just tested it too. [DELPHI 10.3.3 with Alcinoe]

After creating aab file, apks file simulation [32bit & 64bit]

------------

Add ALText / ALRectangle / ALScrollBox / ALTabControl  to the blank form.

Android 64bit-Application Store Mode & [aab option checked]
Build Run.

Project1.aab was created.

Command execution
java -jar "C:\Program Files (x86)\Embarcadero\Studio\20.0\bin\Android\bundletool-all-0.10.3.jar" build-apks --bundle="Project1.aab" --output=extracted .apks --adb="C:\Users\Public\Documents\Embarcadero\Studio\20.0\CatalogRepository\AndroidSDK-2525_20.0.36039.7899\platform-tools\adb.exe" --ks="D:\test\ testtt\key\mykey.keystore" --ks-pass=pass:tfod777 --ks-key-alias=mykey --key-pass=pass:tfod777

extracted.apks are created
(32bit & 64bit included)

Run test on Android7 Android10

Perfect operation

armeabi_v7a.apk & arm64_v8a.apk files... all ok!
