### ISSUE TITLE
Exoplayer can't play media from uri with username and password

### ISSUE THREAD

**Issue by dune3000** [MagicFoundation/Alcinoe#156]
Hi, 
I want to play media from tvheadend with user authentication, the uri like http://username:password@tvh.ip/xxxxxxxx
after google, found this solution 
https://stackoverflow.com/questions/21906749/stream-authenticated-video-with-mediaplayer-on-android

looks like need  to add DefaultHttpDataSource to exoplayer api

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
