### ISSUE TITLE
Resume video playback after app gets active again

### ISSUE THREAD

**Issue by GitUserMarkus** [MagicFoundation/Alcinoe#157]
I use TALVideoPlayer in my app and have problems to resume the video playback after the app has been pushed to the background and is revoked again. I have read about solutions to that problem on Stack Exchange for Exoplayer and AVPlayer however it seems to me that TALVideoPlayer does not give access to some of the attributes of Exoplayer resp. AVPlayer that seem to need a refresh.
Could you (someone) please help and explain what to do such that the player is not freezing after the app is resumed?
Many thanks in advance.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
