### ISSUE TITLE
I have a question about how to use TALVertScrollbox among Alcinoe components.

### ISSUE THREAD

**Issue by LeeHyunChul777** [MagicFoundation/Alcinoe#160]
I have a question about how to use TALVertScrollbox among Alcinoe components.

I am so happy that it is much faster than the Delphi basic TVertScrollbox.

By the way, when the top or bottom is already reached, scrolling is added. Can this be prevented? 
Perhaps it was created for animation effects.

And one more thing

When placing TMemo on TALVertScrollbox, there is a bug that Memo does not work. (Keyboard does not appear on Android. Galaxy Note Android 10)

Anyone would appreciate it.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
