### ISSUE TITLE
TALMacOSVideoPlayer implementation

### ISSUE THREAD

**Issue by TetrisSQC** [MagicFoundation/Alcinoe#164]
Hi, 
I added a TALMacOSVideoPlayer implementation based on the OpenGLES implementation for IOS. This was quite straight forward, but I did not got the OpenGL renderer working. What I did is adding the metal video framework for the OS X playback. 

[macos.txt](https://github.com/Zeus64/alcinoe/files/5866605/macos.txt)
<img width="1392" alt="Bildschirmfoto 2021-01-24 um 11 27 41" src="https://user-images.githubusercontent.com/11291557/105627555-eac62b00-5e37-11eb-8e5f-e5a75747276f.png">

**Comment by TetrisSQC** [comment]
Okay, i tested it here and it fails on CVOpenGLTextureCacheCreate. The rest runs (if you ignore the video playback) fine. I have to investigate this a bit further.

**Comment by Zeus64** [comment]
Hi TetrisSQC, I m really sorry but the TALMacOSVideoPlayer is not yet implemented :( the VideoPlayer work only on mobile (Ios/Android) yet. I don't have any plan to make it working on desktop.

**Comment by TetrisSQC** [comment]
You probably misunderstood my post above. It contains the complete implementation for the MacOS video player. I also made one for Windows which uses ffmpeg and also runs on all other platforms.

**Comment by azrael11** [comment]
TetrisSQC That is great news can you merge it with the main brance

**Comment by Zeus64** [comment]
@TetrisSQC yes I didn't understand this ! that a great news ! I will try to merge it asap

**Comment by TetrisSQC** [comment]
Sure, the attached zip contains the patched code for your alvideoplayer.pas. I think I kept your coding style intact. The demo is an example which should play a stream under MacOS, iOS and Android.

[osxplayer.zip](https://github.com/Zeus64/alcinoe/files/6245368/osxplayer.zip)

Christian

**Comment by azrael11** [comment]
> 
> 
> Sure, the attached zip contains the patched code for your alvideoplayer.pas. I think I kept your coding style intact. The demo is an example which should play a stream under MacOS, iOS and Android.
> 
> [osxplayer.zip](https://github.com/Zeus64/alcinoe/files/6245368/osxplayer.zip)
> 
> Christian

Please make an example with windows ffmpeg video player.

**Comment by TetrisSQC** [comment]
Oh this one is missing, it will require some time to add since I used parts of a commercial code project. You could also use this project https://github.com/TetrisSQC/StreamPlayer.

The implementation then looked like this:

`constructor TALWinVideoPlayer.Create;
begin
  inherited;
  fOnFrameAvailableEvent := nil;
  fOnCompletionEvent := nil;
  fOnErrorEvent := nil;
  FOnPreparedEvent := nil;
  fonVideoSizeChangedEvent := nil;

  FPlayer := TAVPlayer.create(nil);
  FPlayer.HardwareAccelerated := true;
  FPlayer.ForceYV12 := true;
  fbitmap := TAVBitmap.create(nil);
  fbitmap.Player := FPlayer;
  fBitmap.OnUpdate := doOnFrameRefresh;
  fbitmap.onResize := doOnVideoSizeChanged;
end;

{ *********************************** }
destructor TALWinVideoPlayer.Destroy;
begin
  alFreeandNil(fbitmap);
  alFreeandNil(FPlayer);
  inherited;
end;

{ *************************************************** }
function TALWinVideoPlayer.getCurrentPosition: int64;
begin
  result := Trunc(FPlayer.Position*1000);
end;

{ ******************************************** }
function TALWinVideoPlayer.getDuration: int64;
begin
  result := Trunc(FPlayer.Duration*1000);
end;

{ ************************************************* }
function TALWinVideoPlayer.getVideoHeight: Integer;
begin
  result := FPlayer.VideoHeight;
end;

{ ************************************************ }
function TALWinVideoPlayer.getVideoWidth: Integer;
begin
  result := FPlayer.VideoWidth;
end;

{ ******************************************** }
function TALWinVideoPlayer.isPlaying: Boolean;
begin
  result := FPlayer.Playing;
end;

{ ******************************** }
procedure TALWinVideoPlayer.pause;
begin
 FPlayer.Pause;
end;

{ ************************************************************* }
procedure TALWinVideoPlayer.prepare(Const aDataSource: String);
begin
 FPlayer.OpenMovie(aDataSource);
end;

{ ******************************** }
procedure TALWinVideoPlayer.Start;
begin
 FPlayer.Play;
end;

{ ******************************* }
procedure TALWinVideoPlayer.Stop;
begin
 FPlayer.CloseMovie;
end;

{ **************************************************** }
procedure TALWinVideoPlayer.doOnFrameRefresh(Sender: TObject);
begin
if assigned(fOnFrameAvailableEvent) then
        fOnFrameAvailableEvent(Self);
end;

procedure TALWinVideoPlayer.doOnVideoSizeChanged(Sender: TObject);
begin
 if assigned(fonVideoSizeChangedEvent) then
  fonVideoSizeChangedEvent(self, FBitmap.Bitmap.Width, FBitmap.Bitmap.Height);
end;

{ **************************************************** }
procedure TALWinVideoPlayer.seekTo(const msec: int64);
begin
 FPlayer.Position := msec/1000;
end;

{ ************************************************************* }
procedure TALWinVideoPlayer.setLooping(const looping: Boolean);
begin
end;

{ ********************************************************* }
procedure TALWinVideoPlayer.setVolume(const Value: Single);
begin
 FPlayer.Volume := Value;
end;

{ **************************************************************** }
procedure TALWinVideoPlayer.setPlaybackSpeed(const Value: Single);
begin
 // not implemented
end;

{ ******************************************* }
function TALWinVideoPlayer.getState: Integer;
begin
  result := vpsIdle;
end;

`

I might try to assemble this after easter.

**Comment by TetrisSQC** [comment]
![ffmpeg](https://user-images.githubusercontent.com/11291557/113340124-c4d37000-932b-11eb-8bf1-e11f2f4642cd.PNG)
<img width="1392" alt="Bildschirmfoto 2021-04-01 um 20 48 21" src="https://user-images.githubusercontent.com/11291557/113340130-c866f700-932b-11eb-80e3-408c486c3d8b.png">

The performance in both cases is surprisingly good. I had to convert the YUY image in ffmpeg to RGB32 to paint it in the video surface rectangle.
