### ISSUE TITLE
Issue with colors in iOS app when using GlobalUseMetal := True

### ISSUE THREAD

**Issue by enri690** [MagicFoundation/Alcinoe#168]
Hi. Thank you for the update for last version of Sydney. I have an issue with the rendering of an alrectangle with Bitmap fill (Png, Jpg) when I use **GlobalUseMetal := True;** in my project as it greatly increases speed in **iOS**. The problem is a Hue shift in colors of the image such as red to blue, cyan to yellow and so on.

Edit...    Just added GlobalUseMetal := True; to the ALFmxControls project and it shows there too in every control, plus alvideoplayer also I think is the source of the app crashes.

**Comment by Zeus64** [comment]
hi @enri690 yes actually GlobalUseMetal := True is not yet supported. I don't think their will be much to do to migrate to Metal (except maybe in ALVideoPlayer), but I prefere to reclassify this issue as new feature

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
