### ISSUE TITLE
Error in update.bat

### ISSUE THREAD

**Issue by juanml1979** [MagicFoundation/Alcinoe#172]
Hello

Your components look great

I am following step by step installation instructions. 

Sorry if I made any silly mistakes

I have executed embarcadero\sydney\10_4_2_2update.bat

The backup is correct (fmx and rtl folders are created in embarcadero\sydney\10_4_2)

But the GIT command gives me the following errors:

132 file(s) copied.

....
Patch the source code
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.Helpers.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.Helpers.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Context.GLES.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX/FMX.Context.GLES.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Controls.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX/FMX.Controls.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Dialogs.iOS.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX/FMX.Dialogs.iOS.pas: No such file or directory
....

Can't find the files, but I don't know how to indicate that the correct path is before C:\Program Files (x86)

Could you please help me?

Thank you very much

**Comment by Zeus64** [comment]
You need to have Alexandria 11.3 with the firemonkey source code included
