### ISSUE TITLE
Unable to compile demos project file

### ISSUE THREAD

**Issue by fzkangle** [MagicFoundation/Alcinoe#176]
[Exec Error] The command "PATH C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2020\IDE_spoof;d:\Program Files (x86)\Embarcadero\Studio\20.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;d:\Program Files (x86)\Embarcadero\Studio\20.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\android-system\jdk\bin;D:\android-system\jdk\jre\bin;D:\android-system\android-sdk-windows;C:\Program Files\Git\cmd;D:\android-system\android\android-ndk-r17;D:\android-system\android\android-ndk-r17;D:\android-system\android-sdk-windows;D:\android-system\apache-maven-3.6.3\bin;C:\Program Files\OpenSSL-Win64\bin;D:\Program Files (x86)\Embarcadero\Studio\20.0\bin\converters\java2op; & "D:\android-system\android-sdk-windows\build-tools\24.0.1\dx.bat" --dex --output="D:\DelphiControl\alcinoe-master10.3\alcinoe-master\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "D:\DelphiControl\alcinoe-master10.3\alcinoe-master\lib\jar\org.webrtc\webrtc.jar"" exited with code 1.

**Comment by Zeus64** [comment]
try to run in command prompt the instruction

C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2020\IDE_spoof;d:\Program Files (x86)\Embarcadero\Studio\20.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;d:\Program Files (x86)\Embarcadero\Studio\20.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;D:\android-system\jdk\bin;D:\android-system\jdk\jre\bin;D:\android-system\android-sdk-windows;C:\Program Files\Git\cmd;D:\android-system\android\android-ndk-r17;D:\android-system\android\android-ndk-r17;D:\android-system\android-sdk-windows;D:\android-system\apache-maven-3.6.3\bin;C:\Program Files\OpenSSL-Win64\bin;D:\Program Files (x86)\Embarcadero\Studio\20.0\bin\converters\java2op; & "D:\android-system\android-sdk-windows\build-tools\24.0.1\dx.bat" --dex --output="D:\DelphiControl\alcinoe-master10.3\alcinoe-master\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "D:\DelphiControl\alcinoe-master10.3\alcinoe-master\lib\jar\org.webrtc\webrtc.jar"

and please write here the output

**Comment by fzkangle** [comment]
PARSE ERROR:
unsupported class file version 52.0
...while parsing org/webrtc/androidvideodecoder.class
1 error;aborting

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
