### ISSUE TITLE
Runtime error in ALLiveVideoChatClient

### ISSUE THREAD

**Issue by filiptoskovic** [MagicFoundation/Alcinoe#177]
I have successfully compiled ALLiveVideoChatClient on Amdroid32/64 platforms using Delphi 10.4.2. To achieve that I have done these steps:
1. Updated original Delphi files by Update.bat found in "alcinoe\embarcadero\sydney\10_4_2"
2. Added path to Alcinoe source files to compiler's search path
3. Changed original dx.bat in "C:\Users\Public\Documents\Embarcadero\Studio\21.0\CatalogRepository\AndroidSDK-2525-21.0.40680.4203\build-tools\29.0.3" with dx.bat file from "alcinoe\tools\D8Proxy"
4. Updated path in dx.bat file, line 50, original path was "C:\SDKs\android\platforms\android-30" an I have changed it to "C:\Users\Public\Documents\Embarcadero\Studio\21.0\CatalogRepository\AndroidSDK-2525-21.0.40680.4203\platforms\android-29\android.jar" where my android.jar really is
5. Created "C:\Dev\Alcinoe\lib\jar" and copied content of "alcinoe\lib\jar" there

I can compile on both android platforms with these steps but I got runtime error : "First chance exception at $0000007627129C40. Exception class EJNIException with message 'java.lang.NoClassDefFoundError: Failed resolution of: Lorg/webrtc/PeerConnectionFactory$InitializationOptions;'. Process ALLiveVideoChatClient.apk (1699)"

How to solve this problem?

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
