### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by fzkangle** [MagicFoundation/Alcinoe#181]
EXEC : Uncaught translation error : com.android.dx.cf.code.SimException: ERROR in com.alcinoe.webrtc.ALWebRTC.<init>:(Landroid/content/Context;Landroid/opengl/EGLContext;Ljava/util/List;Lcom/alcinoe/webrtc/ALWebRTC$PeerConnectionParameters;)V: invoking a static interface method org.webrtc.EglBase.createEgl14:(Landroid/opengl/EGLContext;[I)Lorg/webrtc/EglBase; strictly requires --min-sdk-version >= 24 (blocked at current API level 13)

**Comment by Zeus64** [comment]
when exacly you have this error ?

**Comment by Zeus64** [comment]
seam it's quite new that now you need --min-sdk-version >= 24 to use createEgl14, can you say a little more what you do to receive this error ?
