### ISSUE TITLE
TAlMemo crash in Android with Delphi 10.4.2

### ISSUE THREAD

**Issue by nsayingil** [MagicFoundation/Alcinoe#185]
Hello guys.

Into form put a TAlMemo controls. Then I try run into my Android device, but I see the next message:

$BFB37565. Exception class EJNIException with message 'java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader java.lang.Class.getClassLoader()' on a null object reference'. Process Project1.apk (6609)

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
