### ISSUE TITLE
Fail run update.bat

### ISSUE THREAD

**Issue by dediajimk** [MagicFoundation/Alcinoe#194]
Dear Zeus64
I have trouble to update Alcino. here by I Submit the SS
![2021-06-13_211215](https://user-images.githubusercontent.com/16104047/121810756-42045500-cc8c-11eb-844a-4e2d45873b9f.png)

and here is the folder of update.bat
![2021-06-13_211505](https://user-images.githubusercontent.com/16104047/121810836-8263d300-cc8c-11eb-93c3-34374b4189c7.png)

Please how to solve it?

**Comment by Zeus64** [comment]
can you try in the command prompt to go in the directory where the update.bat is located and run from this directory update.bat ?

**Comment by Zeus64** [comment]
Hello can you try to update the repository to the very last version and run again update.bat ?

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
