### ISSUE TITLE
Firebase Messaging

### ISSUE THREAD

**Issue by zomorango** [MagicFoundation/Alcinoe#195]
Hi,
I have compiled the ALFirebaseMessaging to my iphone ios 14.5, it work and I receive the token, but when I Try to test sending notifications on reqbin.com I never get any notification
this is the result of the test
`{
    "multicast_id": 8197257866929898643,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [{
        "message_id": "0:1623829887551557%8a89a1bff9fd7ecd"
    }]
}`

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
