### ISSUE TITLE
error linking demo sydney 10_4_2

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#198]
Error:
update.bat 
I did not install development for ios
to me have to manually delete everything related to iOS on BAT as well with sydney_10_4_2.patch

**Comment by firemen01** [comment]
zamenil v ustanovlennoy del'fi tri fayla na vashi
48 / 5000
Результаты перевода
replaced three files in the installed delphi with yours: ALFMXTypes3D.pas; FMX.Canvas.GPU.Helpers.pas; FMX.Context.GLES.pas
http://my.encore.su:8080/download/test.zip
I can't play the video in any way.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
