### ISSUE TITLE
camera recording

### ISSUE THREAD

**Issue by IgorMarinin** [MagicFoundation/Alcinoe#200]
Please tell me how you can record video from a camera to a file?
I would like to implement the ability to record a video message by the user, then send the already received video file, if necessary.
for example, when there is no Internet, so that the user can record a video message.
I would also like to try to implement a type of karaoke player so that the user can record a video of his performance of the song to a file. is it possible to do this using your library?
good luck!

**Comment by Zeus64** [comment]
Unfortunatly this is not yet supported :(
