### ISSUE TITLE
Visual Component disappear (Trackbar)

### ISSUE THREAD

**Issue by MichaelLurie** [MagicFoundation/Alcinoe#203]
Hi
I placed some trackbars on my form and behaviour is absolutely normal. After closing the app and reopening  Delphi reports that it can't find TALTrackbar. Component is installed and I can place a new trackbar on the form, but the ones saved are not displayed anymore.

Delphi Rio 10.3.3

Any advice would be gratly appreciated
Michael

**Comment by Zeus64** [comment]
hi Michael, this seam very strange, like the TALTrackbar is not installed when the form is opened :( Never heard that

**Comment by MichaelLurie** [comment]
It might have to do with Frames. Maybe you can recreate it. If I put the trackbar on a normal form it seems okay. On a frame they disappear.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
