### ISSUE TITLE
a question please

### ISSUE THREAD

**Issue by RDP1974** [MagicFoundation/Alcinoe#217]
does webrtc fmx works in mac osx ?

**Comment by Zeus64** [comment]
right now now not, but it's could work, someone even gave me a patch to make it working in osX, just need to find time to merge it :(

**Comment by RDP1974** [comment]
Can be useful a compiled webrtc library for osx? Do you will build a WebRtcOsxAPI.pas over it?

Roberto Della Pasqua
Software |> Architect |> Developer

Microsoft C. of Excellence
Embarcadero C. of Excellence
American Design Award
Social Network Patents
Smart Industry 4.0
School Teacher
Mystic Book Author

www.dellapasqua.com<https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.dellapasqua.com%2F&data=04%7C01%7C%7C94f55caab532433500e208d909a40dde%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637551422471501847%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P5P8sOMtVm2PT%2FuDLpkagyZnhvkC4c6T2pA6%2FYGj2Mc%3D&reserved=0>
***@***.******@***.***

Da: Zeus64 ***@***.***>
Inviato: lunedì 13 settembre 2021 14:52
A: Zeus64/alcinoe ***@***.***>
Cc: Roberto Della Pasqua ***@***.***>; Author ***@***.***>
Oggetto: Re: [Zeus64/alcinoe] a question please (#217)


right now now not, but it's could work, someone even gave me a patch to make it working in osX, just need to find time to merge it :(

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZeus64%2Falcinoe%2Fissues%2F217%23issuecomment-918159069&data=04%7C01%7C%7C90c8d84df31649e1581e08d976b5541d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637671343427480211%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yeb0RYJELL3wk5Mg7WmGviUQMyYSCw5Dn9VuFtULxZo%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASJYYI65WV5UXMIW2N4EDJLUBXXYLANCNFSM5D5XGPAA&data=04%7C01%7C%7C90c8d84df31649e1581e08d976b5541d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637671343427490157%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BAR4tGEV7R%2Bx%2BhgesWKallWYXTCCXhZUsAgtVu6LgDg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C90c8d84df31649e1581e08d976b5541d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637671343427500087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yW1gixYOsP%2FIqsBg1GGM0vFWHYt1FiTGjLwKB89Uu%2FM%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C90c8d84df31649e1581e08d976b5541d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637671343427500087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=65WSZimUS5MYVEmSiogvwtUiATd6FrFiU1PRIFdujqY%3D&reserved=0>.

**Comment by Zeus64** [comment]
hello, do you succeed to use webRTC ?
