### ISSUE TITLE
Caching of Video-Stream

### ISSUE THREAD

**Issue by GitUserMarkus** [MagicFoundation/Alcinoe#218]
I am using ALVideoPlayer to play hls (m3u8) videos. On Android the player (exoplayer) crashes quite often when the playback speed is larger than 1 (faster than original speed). To me it seems that there is a buffering/caching issue, i.e. the player seems to run out of data in case of faster playback, for the crashes do not occur if speed is the original one.
I use a fast WLAN connection and an AWS S3 bucket for the video data thus with high probability it is not an issue of bandwidth of network or server.
Any idea?
Many thanks in advance!

**Comment by dondonondon** [comment]
how to use TALvideoPlayerSurface? When i use it, always stuck on splash screen

**Comment by GitUserMarkus** [comment]
Did you add the Exoplayer libraries to your project? If I remember correctly I experienced the very same problems before adding the related java libraries.

**Comment by Zeus64** [comment]
if it's freeze then try to look with the monitor the log (mine is located here: C:\SDKs\android\tools\monitor.bat)
but it's look like you forget one jar, try to launch the alfmxcontrols demo

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
