### ISSUE TITLE
Alkyne compatibility with Delphi 11

### ISSUE THREAD

**Issue by RamonSouza96** [MagicFoundation/Alcinoe#222]
Hi, I'm looking forward to using alcinoe in Delphi 11, I'm waiting for this to migrate, thank you very much for your contribution to the Alcinoe component palette.

**Comment by Zeus64** [comment]
Hi, I planed the to add the support with the Update 1 of Delphi 11

**Comment by okbach** [comment]
+1

**Comment by commanderz** [comment]
just added patched files for compile alcicoe for Delphi 11 Alexandria
https://github.com/commanderz/alcinoe-delphi11-patched
@Zeus64 can use it free if want, and tnanks you, bro, for very cool lib.
( @okbach )

**Comment by Zeus64** [comment]
thanks everythink is done now, alcinoe is fully compatible with alexandria
