### ISSUE TITLE
TALSwitch + Stroke

### ISSUE THREAD

**Issue by kazuser** [MagicFoundation/Alcinoe#234]
![TALSwitch](https://user-images.githubusercontent.com/3335273/153717878-819e70b2-a9f3-4297-af16-a723440770a2.gif)

1. Not drown;
2. Not saved.

**Comment by Zeus64** [comment]
hello kazuer, with version of delphi do you use ?

**Comment by kazuser** [comment]
Delphi 10.4 Version 27.0.40680.4203

[test switch.zip](https://github.com/Zeus64/alcinoe/files/8064783/test.switch.zip)

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
