### ISSUE TITLE
Compatible with custom Canvas

### ISSUE THREAD

**Issue by viniciusfbb** [MagicFoundation/Alcinoe#235]
I know it's a lot of work, but it would be great to have support for custom canvas. For that, there should be some define to use TBitmap instead of TTexture.

**Comment by Zeus64** [comment]
Yes i agree but the problem with Tbitmap (under firemonkey) is that is can not work in background thread :( that a real problem. in other way, TTexture is little more light and can work in background thread (I mean you can create the texture in background thread)

**Comment by viniciusfbb** [comment]
Yes, firemonkey's TBitmap works in background thread, but not in parallel, the TCanvas lock blocks it. It is even possible to draw with the GPU in parallel, but it is a very complex and risky design. The solution used was to let the UI draw with the GPU while all TBitmaps draw with the CPU. That way, the TCanvas lock can even be removed (I even suggested removing it optionally [RSP-37232](https://quality.embarcadero.com/browse/RSP-37232)).

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version, now it's fully compatible with skia
