### ISSUE TITLE
RAD 11.1 released! 

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#236]
RAD 11.1 released.
 
https://altd.embarcadero.com/download/radstudio/11.0/RADStudio_11_1_esd_10_8973a.iso

when to expect alcinoe?

**Comment by Zeus64** [comment]
I m installing it :) look promising !

**Comment by firemen01** [comment]
if you need a crack contact us! )
looking forward to your release for 11.1

**Comment by kazuser** [comment]
![star](https://user-images.githubusercontent.com/3335273/158810453-7488cbb7-5086-41cf-9dea-d2d0955f18d4.gif)

**Comment by commanderz** [comment]
Just added patched files for Delphi 11.1
https://github.com/commanderz/alcinoe-delphi11-patched/tree/delphi_11_1

**Comment by JoseMorango** [comment]
Well I Just give up on Alcinoe lib, non-commercial libraries rarely have a future unless their backed by big companies, It's a same such a good project is dying, I should been better to pay for it 350 ou 400 euros, and 200 for renew, that way I would have neved died.

**Comment by Zeus64** [comment]
Alcinoe is now fully compatible with alexandria
