### ISSUE TITLE
RAD Studio 11.1 Patch 1

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#238]
https://blogs.embarcadero.com/rad-studio-11-1-alexandria-patch-1-available/

http://altd.embarcadero.com/getit/public/libraries/Patches/Patch.R111.Patch1-202204273.zip

please consider this patch.

work going on? ))

**Comment by firemen01** [comment]
are you OK? work moving for 11.1?

**Comment by marlonnardi** [comment]
News? @Zeus64 this project cannot die...

**Comment by firemen01** [comment]
So where did the author go? something is not visible at all, maybe he abandoned his project?

**Comment by JerryMacNow** [comment]
Four months have passed and there is still no new version. 
I have wasted a lot of time, completely pointless. 
It was enough to write a few months ago that you don't want or can't develop this project.

**Comment by JerryMacNow** [comment]
OK, only a serious person has the courage to say - Sorry, I am not in a position to develop this further. And here there were promises, people were just wasting their time waiting.

**Comment by Zeus64** [comment]
Hello Alcinoe is now fully compatible with alexandria
