### ISSUE TITLE
Exoplayer hangs under Android 13

### ISSUE THREAD

**Issue by GitUserMarkus** [MagicFoundation/Alcinoe#253]
I have made my own patch for Alcinoe and fmx such that I am able to use your components under Delphi 11.1 and 11.2. Now I observe an issue that only shows up under Android 13. There, any video starts playing just for a second and then the player freezes. I have no idea what the reason is, presuemably it is necessary to update exoplayer to a more recent release. I am posting this issue because
a) I want to ask if you -- during updating alcinoe to Delphi 11.2 -- or anyone else has made the same experience and if yes, how you resolved the problem, and
b) hint to that problem in case you did not observe it yourself.

**Comment by firemen01** [comment]
share your patch please

**Comment by Zeus64** [comment]
Hi can you update the alcinoe repository to the very last one? now we use the very last version of exoplayer. please look the demo https://github.com/MagicFoundation/Alcinoe/tree/master/Demos/ALFmxControls
