### ISSUE TITLE
[DCC Error] E2291 

### ISSUE THREAD

**Issue by AhmetNuri** [MagicFoundation/Alcinoe#254]
Hello I am testing your tools. I am testing  on11.2 Alexandria .
 That is really useful tools. On Windows working perfect . On Android there are error :

[DCC Error] FMX.Presentation.Android.Style.pas(25): E2291 Missing implementation of interface method JRunnable.run

**Comment by gonzzzales** [comment]
+1. 
@Zeus64, what is the percentage of project readiness for 11.2?
I see a patch for 11.2 has appeared, but still Demo project dont work.
Thanks a lot for your work!!!!!

**Comment by Zeus64** [comment]
Hi can you update the alcinoe repository to the very last one? everything must work fine now
