### ISSUE TITLE
[DCC Fatal Error] JVE.AdMob.pas(15): F2051 Unit System.iOS.Sensors was compiled with a different version of iOSapi.CoreLocation.CLLocationManagerDelegate

### ISSUE THREAD

**Issue by AhmetNuri** [MagicFoundation/Alcinoe#255]
Hello 

I am useing this components. this are useble and funny tools.

I have no error when I use that with Delphi own component(IOS Andori and Windows)
All is working on Android and windwos
if I use this with jveadmob componet on IOS there is error 

error message is : 
[DCC Fatal Error] JVE.AdMob.pas(15): F2051 Unit System.iOS.Sensors was compiled with a different version of iOSapi.CoreLocation.CLLocationManagerDelegate

**Comment by Zeus64** [comment]
Hello, that mean you will need to add System.iOS.Sensors.pas (located in your delphi source folder) in your search path. Please update also the alcinoe repository
