### ISSUE TITLE
Alcinoe websocket unavailabled?

### ISSUE THREAD

**Issue by odyright** [MagicFoundation/Alcinoe#256]
Hi, Thank you for your achievment. 
But i'll like to know how to install / use ALWinHTTPWebSocketClient component?
i add alcinoe in the search path.... i also tried to install via bpl sydney, but it's still unavailable.
![image](https://user-images.githubusercontent.com/4316506/204467606-56aaa8d1-10dc-4c54-aa5c-a648b658ab01.png)

**Comment by Zeus64** [comment]
The demo use the DevExpress components (that quite bad for a demo to include such dependancies in it I agree). you can maybe redo the demo without the devExpress dependancies
