### ISSUE TITLE
ALVideoPlayer error(Android 64bit)

### ISSUE THREAD

**Issue by Aleks2077** [MagicFoundation/Alcinoe#257]
Salam friend! I am use Alcinoe Component Library For Delphi.
I cant build project, i have this error:
[DCC Fatal Error] Unit3.pas(12): F2613 Unit 'ALVideoPlayer' not found.

uses
  System.SysUtils, System.Types, System.UITypes, System.Classes,
  System.Variants,
  FMX.Types, FMX.Controls, FMX.Forms, FMX.Graphics, FMX.Dialogs, FMX.Media,
  FMX.TabControl, FMX.StdCtrls, FMX.Controls.Presentation, FMX.ListView.Types,
  FMX.ListView.Appearances, FMX.ListView.Adapters.Base, FMX.ListView,
  System.Actions, FMX.ActnList, FMX.ListBox, FMX.Layouts, FMX.Objects,
  ALFmxObjects, ALVideoPlayer, ALFmxTabControl, FMX.Ani, ALFmxLayouts,
  ALFmxStdCtrls, ALFmxVideoPlayer;

procedure TForm1.Rectangle1Tap(Sender: TObject; const Point: TPointF);
var
AMedia_Path:String;
begin
AMedia_Path:=TPath.Combine(TPath.GetDocumentsPath, 'demo.mp4');
PlayerSurface.VideoPlayer.setLooping(False);
PlayerSurface.VideoPlayer.prepare(AMedia_Path, true);
PlayerSurface.VideoPlayer.setVolume(0.5);
PlayerSurface.VideoPlayer.Start;
end;

How fix it? Delphi 11, Android 64

**Comment by Aleks2077** [comment]
I cant find in source files ALVideoPlayer (((

**Comment by Aleks2077** [comment]
I wank to make simple videoplayer for Android 11(fullscreen scaling video, landscape oriention)

**Comment by Zeus64** [comment]
Hello, can you try to update the repository and follow the instruction :

If you plan to use FMX (Firemonkey) framework with Alcinoe you will need to patch the original delphi source code. To do this you will need to go in [{alcinoe}\Embarcadero\Alexandria\11_2](https://github.com/MagicFoundation/Alcinoe/tree/master/Embarcadero/Alexandria/11_2/) and run [update.bat](https://github.com/MagicFoundation/Alcinoe/tree/master/Embarcadero/Alexandria/11_2/update.bat) to retrieve and patch the original delphi source code. The batch file assume that the original source code is located in "c:\Program Files (x86)\Embarcadero\Studio\22.0\source" and that you have GIT in your path. Later you will need to include in your project search path all subdirectories located in [{alcinoe}\Embarcadero\Alexandria\11_2](https://github.com/MagicFoundation/Alcinoe/tree/master/Embarcadero/Alexandria/11_2/).

You will need to run [CompileAll.bat](https://github.com/MagicFoundation/Alcinoe/tree/master/CompileAll.bat) to download the iOS/Android libraries, to build the Alcinoe Jars, to build the BPL, to build all tools located in [{alcinoe}\Tools](https://github.com/MagicFoundation/Alcinoe/tree/master/Tools/) and finally to build all demos located in [{alcinoe}\Demos](https://github.com/MagicFoundation/Alcinoe/tree/master/Demos/). NOTE: Some demos use [devexpress](https://www.devexpress.com/)

If you don't plan to use any Alcinoe visual components at design time, then you don't need to install anything, just add [{alcinoe}\Source](https://github.com/MagicFoundation/Alcinoe/tree/master/Source) in the search path of your project.

Else if you want to use visual components at design time then you need to install the bpl. Launch Delphi and go in component > Install Packages... > and choose the BPL located in [{alcinoe}\Libraries\bpl\Alcinoe\Win32\Alexandria\AlcinoeAlexandria.bpl](https://github.com/MagicFoundation/Alcinoe/tree/master/Libraries/bpl/Alcinoe/Win32/Alexandria). You also need to add in your search path [{alcinoe}\Source](https://github.com/MagicFoundation/Alcinoe/tree/master/Source) and all subdirectories located in [{alcinoe}\Embarcadero\Alexandria\11_2](https://github.com/MagicFoundation/Alcinoe/tree/master/Embarcadero/Alexandria/11_2/).

please find a demo at https://github.com/MagicFoundation/Alcinoe/tree/master/Demos/ALFmxControls
