### ISSUE TITLE
Where to find the .bpl files

### ISSUE THREAD

**Issue by Bj0ernald** [MagicFoundation/Alcinoe#258]
It's probably me overlooking something.
But I can't get myself to find any .bpl files in this project.
The path [{alcinoe}\Libraries\bpl\Alcinoe\Win32\Alexandria\AlcinoeAlexandria.bpl] does not exist.
What am I missing?

**Comment by Zeus64** [comment]
You need to execute CompileAll.bat https://github.com/MagicFoundation/Alcinoe/blob/master/CompileAll.bat to generate them

**Comment by p3rf1** [comment]
Sorry for bringing up the subject. I execute CompileAll.bat but the folder in \Alcinoe-master\Libraries does not appear. And the test error:

C:\cmpnts\Alcinoe-master\Source\Alcinoe.FMX.Layouts.pas(144): error E2137: Method 'ChildrenMouseDown' not found in base
 class [C:\cmpnts\Alcinoe-master\Tests\_Source\ALTests.dproj]
C:\cmpnts\Alcinoe-master\Source\Alcinoe.FMX.Layouts.pas(145): error E2137: Method 'ChildrenMouseMove' not found in base
 class [C:\cmpnts\Alcinoe-master\Tests\_Source\ALTests.dproj]
C:\cmpnts\Alcinoe-master\Source\Alcinoe.FMX.Layouts.pas(146): error E2137: Method 'ChildrenMouseUp' not found in base c
lass [C:\cmpnts\Alcinoe-master\Tests\_Source\ALTests.dproj]
C:\cmpnts\Alcinoe-master\Source\Alcinoe.FMX.Layouts.pas(147): error E2137: Method 'ChildrenMouseLeave' not found in bas
e class [C:\cmpnts\Alcinoe-master\Tests\_Source\ALTests.dproj]
ALTests.dpr(194): error F2063: Could not compile used unit 'Alcinoe.FMX.Layouts.pas' [C:\cmpnts\Alcinoe-master\Tests\_S
ource\ALTests.dproj]
