### ISSUE TITLE
Alcione 11.2

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#260]
no find InitEnvironment.bat

**Comment by firemen01** [comment]
how to build an exoplayer jar?

**Comment by Zeus64** [comment]
Hi, can you update again the repository? normally you must have now the InitEnvironment.bat. you do not need to build any more the exoplayer.jar. please take a look at https://github.com/MagicFoundation/Alcinoe/tree/master/Demos/ALFmxControls (try to run the demo). and also take a look at [c:\Dev\MagicFoundation\Alcinoe\Demos](https://github.com/MagicFoundation/Alcinoe/tree/master/Demos)\ALFmxControls\_source\android\MergeLibraries.bat on how to import the exoplayer library in your project

**Comment by Zeus64** [comment]
Hi, please update your repository with the very last version of alcinoe. now everything must work well

**Comment by firemen01** [comment]
thanks!
your project ALFMXControls is going up and running.
I can't collect mine yet.
guava.  is it needed for the video player at all?

I collect through ide, simply replacing / adding *.jar from your project

[PAClient Error] Error: E7688 Error in D:\Programm\Android\Release\com.google.guava-failureaccess-1.0.1-dexed.jar:classes.dex:
[PAClient Error] Error: E7688 Type com.google.common.util.concurrent.internal.InternalFutureFailureAccess is defined multiple times: D:\Programm\Android\Release\com.google.guava-failureaccess-1.0.1-dexed.jar:classes.dex, D:\Programm\Android\Release\com.google.guava-failureaccess-1.0.1-dexed-dexed.jar:classes.dex
[PAClient Error] Error: E7688 Compilation failed

[PAClient Error] Error: E7688 Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: D:\Programm\Android\Release\com.google.guava-failureaccess-1.0.1-dexed.jar:classes.dex
[PAClient Error] Error: E7688 	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:98)
[PAClient Error] Error: E7688 	at com.android.tools.r8.D8.main(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:4)

**Comment by firemen01** [comment]
Oh, I removed it from the libraries: 
   com.google.guava-failureaccess-1.0.1-dexed.jar
   com.google.guava-guava-31.0.1-android-dexed.jar
and it worked.

**Comment by firemen01** [comment]
what kind of *.jar do you need if you use only an exoplayer?
androidx.annotation-annotation-1.3.0.jar; androidx.annotation-annotation-experimental-1.1.0.jar .. ???

**Comment by firemen01** [comment]
in the manifest what is it for:
android:appComponentFactory="androidx.core.app.CoreComponentFactory"  ?

**Comment by firemen01** [comment]
RunTests.bat, build Win32,     unit  DUnitX.Loggers.Console.dcu only win64

ALTests.dpr(17): error F2613: Unit 'DUnitX.Loggers.Console' not found. [\Alcinoe\Tests\_So
urce\ALTests.dproj]

**Comment by Zeus64** [comment]
yes you need DUnitX to run the test, if you didn't installed DUnitX when you installed Delphi, then no worry just skip the test phase in ALCompileALL.bat (it's not needed at all in fact). 

regarding exoplayer dependancies, now (and unfortunatly) with latest version of most of all jar, there is often dozen of dependencies. if you look what the exoplayer require it's :

https://maven.google.com/web/index.html#com.google.android.exoplayer:exoplayer-core:2.18.2
 
from here look the pom :

https://dl.google.com/android/maven2/com/google/android/exoplayer/exoplayer-core/2.18.2/exoplayer-core-2.18.2.pom

`    <dependency>
      <groupId>com.google.android.exoplayer</groupId>
      <artifactId>exoplayer-common</artifactId>
      <version>2.18.2</version>
      <scope>compile</scope>
      <type>aar</type>
    </dependency>
    <dependency>
      <groupId>com.google.android.exoplayer</groupId>
      <artifactId>exoplayer-datasource</artifactId>
      <version>2.18.2</version>
      <scope>compile</scope>
      <type>aar</type>
    </dependency>
    <dependency>
      <groupId>com.google.android.exoplayer</groupId>
      <artifactId>exoplayer-decoder</artifactId>
      <version>2.18.2</version>
      <scope>compile</scope>
      <type>aar</type>
    </dependency>
    <dependency>
      <groupId>com.google.android.exoplayer</groupId>
      <artifactId>exoplayer-extractor</artifactId>
      <version>2.18.2</version>
      <scope>compile</scope>
      <type>aar</type>
    </dependency>
    <dependency>
      <groupId>com.google.android.exoplayer</groupId>
      <artifactId>exoplayer-database</artifactId>
      <version>2.18.2</version>
      <scope>compile</scope>
      <type>aar</type>
    </dependency>
    <dependency>
      <groupId>androidx.annotation</groupId>
      <artifactId>annotation</artifactId>
      <version>1.3.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>androidx.core</groupId>
      <artifactId>core</artifactId>
      <version>1.7.0</version>
      <scope>runtime</scope>
      <type>aar</type>
    </dependency>
  </dependencies>`

and from each of those dependancies you need to redo the job to know each dependencies they also need :( yes at the end it's a lot of dependancies (and one of then require com.google.guava-guava probably). This why I created the project android merger (https://github.com/MagicFoundation/Alcinoe/tree/master/Tools/AndroidMerger) that can do all of this for you in one click. Take a look at https://github.com/MagicFoundation/Alcinoe/blob/master/Demos/ALFmxControls/_source/android/MergeLibraries.bat just run this batch to see it in action.

in the android manifest, regarding in the manifest what is it for:
android:appComponentFactory="androidx.core.app.CoreComponentFactory" ? It's just that one dependancies (don't know with, but one, maybe androidx) say it's need android:appComponentFactory="androidx.core.app.CoreComponentFactory".  but as  android:appComponentFactory="androidx.core.app.CoreComponentFactory" is an attribute of the application tab we can not merge it automatiqually with androidmerger and you need to add it manually

**Comment by firemen01** [comment]
tried it on my project:
...
Merge AndroidManifest
Max MinSdkVersion found in libraries: 16
Update dproj
Exception: Error 5427D8C2-7CC9-45DA-94A2-51B036B7BB50

**Comment by Zeus64** [comment]
can you send me in private just theproj of your private project ?

**Comment by firemen01** [comment]
what email to send?

**Comment by Zeus64** [comment]
try on loki5100-nospam@yahoo.fr

**Comment by Zeus64** [comment]
please can you try again to run https://github.com/MagicFoundation/Alcinoe/blob/master/CompileAll.bat and then your batch again ? 

please be aware that to be able to merge all the resources of all dependancies, androidmerger work in android way, that mean that all your items like


```
        <DeployFile Class="Android_SplashImage426" Configuration="Release" LocalName="$(BDS)\bin\Artwork\Android\FM_SplashImage_426x320.png">
          <Platform Name="Android">
            <Enabled>false</Enabled>
            <Overwrite>true</Overwrite>
            <RemoteName>splash_image.png</RemoteName>
          </Platform>
        </DeployFile>
```

must be set not from the project options but inside a merge directory where you will put all the resouces needed by your project. see sample at https://github.com/MagicFoundation/Alcinoe/tree/master/Demos/ALFmxControls/_source/android/ALFmxControlsApp/res

**Comment by firemen01** [comment]
examples demos gathered all, where there are no third-party modules:

 ALDatabaseBenchmark.dproj, ALStressHTTPServer    Unit 'cxStyles' not found.
 ALJsonDocDemo.dproj  Unit 'VclTee.TeeGDIPlus' not found.
 ALSortedListBenchmark.dproj Unit 'VCLTee.TeEngine' not found.
 ALWinHTTPClientDemo Unit 'cxPCdxBarPopupMenu' not found.
 ALWinHTTPWebSocketClientDemo  Unit 'cxPCdxBarPopupMenu' not found
 ALWinInetHTTPClientDemo  Unit 'cxPCdxBarPopupMenu' not found.

my project under the idea was going fine. 

<DeployFile Class="Android_SplashImage426"
**<Enabled>false</Enabled>**

the new AndroidMerger  one passed without errors, thanks!

**Comment by Zeus64** [comment]
`
ALDatabaseBenchmark.dproj, ALStressHTTPServer Unit 'cxStyles' not found.
ALJsonDocDemo.dproj Unit 'VclTee.TeeGDIPlus' not found.
ALSortedListBenchmark.dproj Unit 'VCLTee.TeEngine' not found.
ALWinHTTPClientDemo Unit 'cxPCdxBarPopupMenu' not found.
ALWinHTTPWebSocketClientDemo Unit 'cxPCdxBarPopupMenu' not found
ALWinInetHTTPClientDemo Unit 'cxPCdxBarPopupMenu' not found.
`

It's because those demo need DevExpress to be compiled :(

**Comment by Zeus64** [comment]
I close this bug but feel free to reopen it if you ecountered a probleme
