### ISSUE TITLE
Problems after using AndroidMerger

### ISSUE THREAD

**Issue by GitUserMarkus** [MagicFoundation/Alcinoe#263]
I have used AndroidMerger for my project getting an updated project which includes fmx.dex.jar as single library file. Now that I want to compile and transfer it to the mobile I get the following errors from paclient:
[PAClient Fehler] Fehler: E2312 ...\AndroidManifest.xml:37: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/ic_launcher').
[PAClient Fehler] Fehler: E2312 ...\AndroidManifest.xml:37: error: Error: No resource found that matches the given name (at 'theme' with value '@style/AppTheme').

I have checked the files within the folder <App>/res/drawable and <App>/res/values and observed that, compared to what was generated before AndroidMerger has changed my project file, the files styles.xml and  splash_image_def.xml are missing in which the requested values formerly were defined.

Any idea what went wrong?

Many thanks in advance!!

**Comment by Zeus64** [comment]
you need to deploy (with androidMerger) those folders :

res\drawable-hdpi
res\drawable-mdpi
res\drawable-xhdpi
res\drawable-xxhdpi
res\drawable-xxxhdpi

with inside those folders the file ic_launcher.png.

regarding @style/AppTheme update your AndroidManifest.template.xml with
`<application ..... android:theme="@android:style/Theme.NoTitleBar">`

**Comment by GitUserMarkus** [comment]
Okay, now the errors are gone but my app does not start (freezes where the splash screen should be shown but without the spalsh image visible).
I did not change anything in my code but using androidMerger.

**Comment by GitUserMarkus** [comment]
Are all the libraries that dephi includes by default (those which are imported when using the IDE to set the default) automatically included by androidMerger?

**Comment by Zeus64** [comment]
Niet (except the fmx.jar) :( 
You need to import them specifically in AndroidMerger with the version you need. When you start your android app look in the log the error you have.

**Comment by Zeus64** [comment]
Regarding the start-up image, you can do it yourself like any android users does, playing with the /res folder, adding in it all the customization you need

**Comment by GitUserMarkus** [comment]
Thanks again, exoplayer now works (I used a wrong search path to unpatched source files).

**Comment by Zeus64** [comment]
perfect :)
