### ISSUE TITLE
Failed patch file FMX.Controls.pas on Delphi Alexandria last patch 

### ISSUE THREAD

**Issue by amancini** [MagicFoundation/Alcinoe#265]
the FMX.Controls.pas file is not changed by the Alexandria_11_2.patch patch,

The function that fails is ConvertLocalPointFrom

best regards
Alessandro Mancini

**Comment by Zeus64** [comment]
with version of alexandria do you have? the patch work with Alexandria 11.2

**Comment by amancini** [comment]
11.1

**Comment by Zeus64** [comment]
So you need to update to 11.2 the patch work only with the 11.2

**Comment by amancini** [comment]
ok thanks
