### ISSUE TITLE
ALLiveVideoChat

### ISSUE THREAD

**Issue by kabiri** [MagicFoundation/Alcinoe#266]
hello
when a comiple ALLiveVideoChat.groupproj delphi show error in Alcinoe.FMX.Layouts (in android & windows)
for ios unit Alcinoe.FMX.Graphics has error

**Comment by Zeus64** [comment]
Can you show the details of the error please ?

**Comment by kabiri** [comment]
> Can you show the details of the error please ?
IOS :
[DCC Error] Alcinoe.FMX.Graphics.pas(3432): E2003 Undeclared identifier: 'kCIInputImageKey'
[DCC Error] Alcinoe.FMX.Graphics.pas(3436): E2003 Undeclared identifier: 'kCIInputRadiusKey'
[DCC Error] Alcinoe.FMX.Graphics.pas(3622): E2003 Undeclared identifier: 'kCIInputImageKey'

Android & windows :
[DCC Error] Alcinoe.FMX.Layouts.pas(146): E2137 Method 'ChildrenMouseDown' not found in base class
[DCC Error] Alcinoe.FMX.Layouts.pas(147): E2137 Method 'ChildrenMouseMove' not found in base class
[DCC Error] Alcinoe.FMX.Layouts.pas(148): E2137 Method 'ChildrenMouseUp' not found in base class
[DCC Error] Alcinoe.FMX.Layouts.pas(149): E2137 Method 'ChildrenMouseLeave' not found in base class

**Comment by Zeus64** [comment]
yes you must execute https://github.com/MagicFoundation/Alcinoe/blob/master/Embarcadero/Alexandria/11_2/Update.bat before

**Comment by kabiri** [comment]
OK
Thanks
