### ISSUE TITLE
Path source, Merge

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#267]
I propose to separate the patches, since you have to clean everything with your hands, who does not have everything installed.
Update.bat
```
.....
echo Patch the source code
CHDIR ".\..\..\..\"

git apply --ignore-space-change --ignore-whitespace .\Embarcadero\Alexandria\11_2\Alexandria_11_2_FMX_WIN.patch -v

IF EXIST "%EmbSourceDir%\rtl\ios" (
git apply --ignore-space-change --ignore-whitespace .\Embarcadero\Alexandria\11_2\Alexandria_11_2_IOS.patch -v
)
IF EXIST "%EmbSourceDir%\rtl\android" (
git apply --ignore-space-change --ignore-whitespace .\Embarcadero\Alexandria\11_2\Alexandria_11_2_ANDROID.patch -v
)
.....

```

I also suggest adding a key to AndroidMerger so that it copt not only the resources folder, but also all folders with -Libraries,
so that you can immediately use DeployMan. Although it can be transferred by default, because if the user put something there, it means he wants to add it to the installation.
DeployMan is great at adding all custom Merged folders to the project.
But AndroidMerger cleans this folder completely and transfers only resources there, you have to manually copy your files folders there before using DeployMan

AndroidMerger creates, as I understand it, a bunch of all sorts of files for the echoplayer, such as notification*.png, values*.xml?
where are they used? can you delete all of this? everything seems to work fine without them.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
