### ISSUE TITLE
RAD Studio 11.3 Alexandria

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#269]
Do you plan to do support in the near future?

https://altd.embarcadero.com/download/radstudio/11.0/RADStudio_11_3_28_12819a.iso

**Comment by Zeus64** [comment]
Hi yes I will try to follow new release as fast as possible. I m doing the job now

**Comment by Zeus64** [comment]
I will just wait around 1 week before to migrate to 11.3 to be sure that their is no bug in this new release

**Comment by firemen01** [comment]
you don't trust beta testers? )))

**Comment by Zeus64** [comment]
Done in the last commit
