### ISSUE TITLE
CompileAll.bat exits with error 

### ISSUE THREAD

**Issue by GitUserMarkus** [MagicFoundation/Alcinoe#271]
When running CompileAll.bat and asking for a download of the libraries, the following error occurs:

```
Download org.webrtc:google-webrtc:1.0.25331
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.7M  100 25.7M    0     0  21.3M      0  0:00:01  0:00:01 --:--:-- 21.3M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500
```

**Comment by Zeus64** [comment]
Can you try again? I corrected in the last commit

**Comment by GitUserMarkus** [comment]
Now it works, many thanks.

 

However, now in 11.3 I have the very same problem as reported in issue #272, the AlFmxControls-Demo hangs under android after startup. With 11.2 everything worked well after your support with the Merger. Right now I am not sure if it is an issue of my installation but I thought I let you know.

 

Best regards and thanks again 

 

Markus

 
 

Gesendet: Dienstag, 14. März 2023 um 13:44 Uhr
Von: "Zeus64" ***@***.***>
An: "MagicFoundation/Alcinoe" ***@***.***>
Cc: "GitUserMarkus" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [MagicFoundation/Alcinoe] CompileAll.bat exits with error (Issue #271)


 

Can you try again? I corrected in the last commit

**Comment by Zeus64** [comment]
hi, i have corrected the bug in the very last version of Alcinoe. please use androidMerger in your project. This bug was because of the Delphi 11.3 bug : https://quality.embarcadero.com/browse/RSP-40709
