### ISSUE TITLE
Issue in installing in dephi 11.1

### ISSUE THREAD

**Issue by BikayMeisnam** [MagicFoundation/Alcinoe#272]
I install Alcinoe for Delphi Rad studio 11.1, everything got installed when i open for windows it enable components but when i do for android components get disable so what will the solution ..please help

I would like to request you to make a tutorial video on how to install your library in a proper way so that every new comer could easily understand...or easy process like skia installation.

Thank you

**Comment by Zeus64** [comment]
Alcinoe is not tested with Delphi Rad studio 11.1, only with Delphi Rad studio 11.2 and Delphi Rad studio 11.3

**Comment by BikayMeisnam** [comment]
Ok so I upgraded to Rad studio 11.3 ... evrything got install and even i
build an app but the problem is when I run app on my phone it get stuck in
splash screen (default firemonkey screen ) app doesn't open so what will be
the problem..

**Comment by Zeus64** [comment]
I understand, with app get stuck? the demo ?

**Comment by BikayMeisnam** [comment]
I didn't try the demo...but now I tried to open demo it says TCxMemo not
found.ignore and continue

**Comment by Zeus64** [comment]
hi, i have corrected the bug in the very last version of Alcinoe. please use androidMerger in your project. This bug was because of the Delphi 11.3 bug : https://quality.embarcadero.com/browse/RSP-40709
