### ISSUE TITLE
CompileJar.bat 

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#274]
delete %%B in 
```
FOR /F "usebackq tokens=3*" %%A IN (`reg query "HKCU\Software\Embarcadero\BDS\%ALDelphiVersion%" /v RootDir`) DO set DelphiRootDirFromReg=%%A %%B

FOR /F "usebackq tokens=3*" %%A IN (`reg query "HKCU\Software\Embarcadero\BDS\%ALDelphiVersion%\PlatformSDKs\%PlatformSDK%" /v JDKPath`) DO set JDKPath=%%A %%B
```

**Comment by Zeus64** [comment]
Hi,

the path is C:\Program Files (x86)\Embarcadero\Studio\22.0\
%%A = C:\Program
%%B = Files (x86)\Embarcadero\Studio\22.0\
if you remove the %%B then you will have only 
"C:\Program" instead of "C:\Program Files (x86)\Embarcadero\Studio\22.0\"
