### ISSUE TITLE
RTSP stream

### ISSUE THREAD

**Issue by gonzzzales** [MagicFoundation/Alcinoe#277]
Is it possible to view rtsp stream from ip-camera using Alcinoe?

**Comment by Zeus64** [comment]
hello, you mean in android/ios app ? I guess yes

**Comment by gonzzzales** [comment]
yes, using mobile platforms. 
i try to do something like this in AlFMXControl example
`procedure TForm1.ALVertScrollBox1ViewportPositionChange(Sender: TObject;const OldViewportPosition, NewViewportPosition: TPointF);
begin

  if (ALVideoPlayerSurface1.Position.y + ALVideoPlayerSurface1.Height >= NewViewportPosition.Y) and
     (ALVideoPlayerSurface1.Position.y < NewViewportPosition.Y + height) then begin
    if ALVideoPlayerSurface1.VideoPlayer.state in [vpsIdle] then begin
      ALVideoPlayerSurface1.VideoPlayer.setLooping(true);
      ALVideoPlayerSurface1.VideoPlayer.prepare('rtsp://admin:Nbhfvbce1@showroom.clustersystem.ru:5011/RVi/1/1', True{AutoStartWhenPrepared});
    end
    else if ALVideoPlayerSurface1.VideoPlayer.state in [vpsPrepared, vpsPaused] then ALVideoPlayerSurface1.VideoPlayer.Start
    else ALVideoPlayerSurface1.VideoPlayer.AutoStartWhenPrepared := true;
  end
  else begin
    if ALVideoPlayerSurface1.VideoPlayer.state in [vpsStarted] then ALVideoPlayerSurface1.VideoPlayer.Pause
    else ALVideoPlayerSurface1.VideoPlayer.AutoStartWhenPrepared := False;
  end;


  if (ALLayout1.Position.y + ALLayout1.Height >= NewViewportPosition.Y) and
     (ALLayout1.Position.y < NewViewportPosition.Y + height) then begin
    ALAniIndicator1.enabled := true;
  end
  else begin
    ALAniIndicator1.enabled := False;
  end;

  if ALMemo1.Position.Y - NewViewportPosition.Y > clientHeight then ALMemo1.RemoveNativeView
  else ALMemo1.AddNativeView;

  if ALRectangle3.Position.Y - NewViewportPosition.Y > clientHeight then ALEdit1.RemoveNativeView
  else ALEdit1.AddNativeView;

end;`

but i dont see the stream

**Comment by gonzzzales** [comment]
Please, let me know, if it is possible!!!

**Comment by Zeus64** [comment]
Hi @gonzzzales I think it's not possible like this :(
