### ISSUE TITLE
exoPlayer

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#278]
I can not find where the *.jar is loaded during automatic installation. Or do you need to download com.google.android.exoplayer-.. yourself?

unless an empty folder is created http://alcinoe/Libraries/jar/com/google/android/exoplayer/exoplayer-core/2.18.2/

if try via AndroidMerger:
```
Merge resources in <OutputDir>\res
Create r-aab.jar
Exception: Failed to execute "D:\Install\Android\SDK\build-tools\30.0.3\aapt2.exe" link --manifest "d:\Install\Delphi\MyComponent\Alcinoe\Tools\AndroidMerger\tmp\Libraries\com.google.android.exoplayer-exoplayer-core-2.18.2\\AndroidManifest.xml" -o "d:\Install\Delphi\MyComponent\Alcinoe\Tools\AndroidMerger\tmp\linked_res.ap_" -I "D:\Install\Android\SDK\platforms\android-30\android.jar" -R "d:\Install\Delphi\MyComponent\Alcinoe\Tools\AndroidMerger\tmp\compiled_res.flata" --java "d:\Install\Delphi\MyComponent\Alcinoe\Tools\AndroidMerger\tmp\RJava" --auto-add-overlay
D:\Programm\test\merge\Merged\res\values\values.xml:122: error: resource android:attr/lStar not found.
error: failed linking references.
```

**Comment by firemen01** [comment]
Build alcinoe-launchscreen
Build alcinoe-common
d:\Install\Delphi\Alcinoe\Source\Java\com\alcinoe\location\ALGeocoder.java:35: warning: [deprecation] URL(String) in URL has been deprecated
      URL url = new URL(apiServerURL+(apiServerURL.indexOf("?") >= 0 ? "&" : "?")+
                ^
d:\Install\Delphi\Alcinoe\Source\Java\com\alcinoe\location\ALGeocoder.java:190: warning: [deprecation] Locale(String) in Locale has been deprecated
                address = new Address(new Locale(language));
                                      ^
d:\Install\Delphi\Alcinoe\Source\Java\com\alcinoe\location\ALGeocoder.java:233: warning: [deprecation] Locale(String) in Locale has been deprecated
              address = new Address(new Locale(language));
                                    ^
3 warnings
Build alcinoe-datepicker
Build alcinoe-edittext
Build alcinoe-webrtc
d:\Install\Delphi\Alcinoe\Source\Java\com\alcinoe\webrtc\ALWebRTC.java:494: error: unmappable character (0x92) for encoding UTF-8
      // create a Capturer which takes the image/video from the device?s camera.
                                                                      ^
d:\Install\Delphi\Alcinoe\Source\Java\com\alcinoe\webrtc\ALWebRTC.java:895: error: unmappable character (0x97) for encoding UTF-8
      //including the media format. The method takes a single parameter?the session description?and it
                                                                       ^
d:\Install\Delphi\Alcinoe\Source\Java\com\alcinoe\webrtc\ALWebRTC.java:895: error: unmappable character (0x97) for encoding UTF-8
      //including the media format. The method takes a single parameter?the session description?and it
                                                                                               ^
3 errors

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
