### ISSUE TITLE
[dcc64 Fatal Error] UnitMain.pas(21): F2063 Could not compile used unit 'Alcinoe.FMX.Layouts.pas'

### ISSUE THREAD

**Issue by p3rf1** [MagicFoundation/Alcinoe#282]
[dcc64 Error] Alcinoe.FMX.Layouts.pas(144): E2137 Method 'ChildrenMouseDown' not found in base class
[dcc64 Error] Alcinoe.FMX.Layouts.pas(145): E2137 Method 'ChildrenMouseMove' not found in base class
[dcc64 Error] Alcinoe.FMX.Layouts.pas(146): E2137 Method 'ChildrenMouseUp' not found in base class
[dcc64 Error] Alcinoe.FMX.Layouts.pas(147): E2137 Method 'ChildrenMouseLeave' not found in base class
[dcc64 Fatal Error] UnitMain.pas(21): F2063 Could not compile used unit 'Alcinoe.FMX.Layouts.pas'

use 11.3

**Comment by p3rf1** [comment]
The patch completed, but did not notice the change in FMX.Controls.pas
Maybe someone knows what the problem is?

**Comment by p3rf1** [comment]
Okay, the answer from filiptoskovic in the  [https://github.com/MagicFoundation/Alcinoe/issues/173](thread)  changed things a bit:


C:\Windows\System32>cd C:\Users\Admin\Desktop\compnts\Alcinoe-master

C:\Users\Admin\Desktop\compnts\Alcinoe-master>git apply Embarcadero\Alexandria\11_3\Alexandria_11_3.patch -v
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Canvas.D2D.pas...
Hunk #1 succeeded at 2898 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Canvas.GPU.Helpers.pas...
Hunk #1 succeeded at 16 (offset 1 line).
Hunk #2 succeeded at 314 (offset 1 line).
Hunk #3 succeeded at 427 (offset 1 line).
Hunk #4 succeeded at 437 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Canvas.GPU.pas...
Hunk #1 succeeded at 73 (offset 1 line).
Hunk #2 succeeded at 1215 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Context.GLES.pas...
Hunk #1 succeeded at 189 (offset 1 line).
Hunk #2 succeeded at 1313 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Controls.pas...
Hunk #1 succeeded at 116 (offset 1 line).
Hunk #2 succeeded at 516 (offset 1 line).
Hunk #3 succeeded at 2226 (offset 1 line).
Hunk #4 succeeded at 2233 (offset 1 line).
Hunk #5 succeeded at 2276 (offset 1 line).
Hunk #6 succeeded at 2307 (offset 1 line).
Hunk #7 succeeded at 3699 (offset 1 line).
Hunk #8 succeeded at 4145 (offset 1 line).
Hunk #9 succeeded at 4155 (offset 1 line).
Hunk #10 succeeded at 4447 (offset 1 line).
Hunk #11 succeeded at 4572 (offset 1 line).
Hunk #12 succeeded at 4595 (offset 1 line).
Hunk #13 succeeded at 4604 (offset 1 line).
Hunk #14 succeeded at 4619 (offset 1 line).
Hunk #15 succeeded at 6076 (offset 1 line).
Hunk #16 succeeded at 7234 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Filter.pas...
Hunk #1 succeeded at 608 (offset 1 line).
Hunk #2 succeeded at 839 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Forms.pas...
Hunk #1 succeeded at 4375 (offset 1 line).
Hunk #2 succeeded at 4855 (offset 1 line).
Hunk #3 succeeded at 5635 (offset 1 line).
Hunk #4 succeeded at 5932 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Platform.iOS.pas...
error: Embarcadero/Alexandria/11_3/fmx/FMX.Platform.iOS.pas: No such file or directory
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Platform.UI.Android.pas...
Hunk #1 succeeded at 27 (offset 1 line).
Hunk #2 succeeded at 42 (offset 1 line).
Hunk #3 succeeded at 2777 (offset 1 line).
Hunk #4 succeeded at 2787 (offset 1 line).
Hunk #5 succeeded at 2795 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.Presentation.Android.Style.pas...
Hunk #1 succeeded at 72 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/fmx/FMX.VirtualKeyboard.Android.pas...
Hunk #1 succeeded at 219 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/rtl/android/Androidapi.JNI.App.pas...
Hunk #1 succeeded at 17 (offset 1 line).
Hunk #2 succeeded at 78 (offset 1 line).
Hunk #3 succeeded at 1485 (offset 1 line).
Hunk #4 succeeded at 1569 (offset 1 line).
Hunk #5 succeeded at 1829 (offset 1 line).
Hunk #6 succeeded at 2292 (offset 1 line).
Checking patch Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.AVFoundation.pas...
error: Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.AVFoundation.pas: No such file or directory
Checking patch Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.CoreImage.pas...
error: Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.CoreImage.pas: No such file or directory
Checking patch Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.CoreLocation.pas...
error: Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.CoreLocation.pas: No such file or directory
Checking patch Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.Foundation.pas...
error: Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.Foundation.pas: No such file or directory
Checking patch Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.Security.pas...
error: Embarcadero/Alexandria/11_3/rtl/ios/iOSapi.Security.pas: No such file or directory
Checking patch Embarcadero/Alexandria/11_3/rtl/win/Winapi.Isapi2.pas...
Hunk #1 succeeded at 398 (offset 1 line).

but did not notice the change in FMX.Controls.pas!!!!!
WHAT AM I DOING WRONG? HELP
DROP THIS FMX.Controls.pas PLEASE

**Comment by p3rf1** [comment]
I had to fix everything manually
 now the scrollbox works correctly

**Comment by p3rf1** [comment]
фак ит

**Comment by Zeus64** [comment]
Hi I not understand, you mean the FMX.Controls.pas was not updated ?

**Comment by p3rf1** [comment]
> Привет, я не понимаю, вы имеете в виду, что FMX.Controls.pas не был обновлен?
Yes, the FMX.Controls.pas file along the path \Alcinoe-master\Embarcadero\Alexandria\11_3\fmx was not patched, there were no changes in it, incl. new procedures ChildrenMouseDown, ChildrenMouseMove, ChildrenMouseUp, ChildrenMouseLeave, although the patch log said otherwise

**Comment by Zeus64** [comment]
strange, with version of delphi do you have? the 11.3 or 11.2?

**Comment by p3rf1** [comment]
11.3

> strange, with version of delphi do you have? the 11.3 or 11.2?

**Comment by p3rf1** [comment]
Yes, latest install version for Windows from official website. All files not patched. But the log in cmd says that there were changes.
I use Windows 10 Pro 22H2 ( VMWare virtual machine )

Sorry, I may have mistranslated your question, I use google translate

**Comment by p3rf1** [comment]
My actions:
1. Launched the file Update.bat from the folder Alcinoe-master\Embarcadero\Alexandria\11_3 . All files were successfully copied to folders "fmx" and "rtl". Then log write in post https://github.com/MagicFoundation/Alcinoe/issues/282#issuecomment-1497763032: 

But did not notice the change in ALL files .pas. They remain original.

2. Launched separate window cmd and wrote 
       cd C:\Users\Admin\Desktop\compnts\Alcinoe-master 
            git apply Embarcadero\Alexandria\11_3\Alexandria_11_3.patch -v
Then log write in post https://github.com/MagicFoundation/Alcinoe/issues/282#issuecomment-1497763032
But did not notice the change in ALL files .pas. They remain original.

3. Manually made changes to the file FMX.Controls.pas. And everything worked, but only for the scrollbox. I haven't touched the rest of the files... for now

**Comment by Zeus64** [comment]
> Sorry, I may have mistranslated your question, I use google translate

You need to try chatGPT instead to translate, it's astonishing :) 

Regarding why no files was changed I have no idea where the probleme could be it's very strange. Could you try inside a fresh new VM to install GIT for windows, copy the folder c:\Program Files (x86)\Embarcadero\Studio\22.0\source\ from your alexandria 11.3 and then try again to launch Alcinoe\Embarcadero\Alexandria\11_3\Update.bat ?

**Comment by gonzzzales** [comment]
> [dcc64 Error] Alcinoe.FMX.Layouts.pas(144): E2137 Method 'ChildrenMouseDown' not found in base class [dcc64 Error] Alcinoe.FMX.Layouts.pas(145): E2137 Method 'ChildrenMouseMove' not found in base class [dcc64 Error] Alcinoe.FMX.Layouts.pas(146): E2137 Method 'ChildrenMouseUp' not found in base class [dcc64 Error] Alcinoe.FMX.Layouts.pas(147): E2137 Method 'ChildrenMouseLeave' not found in base class [dcc64 Fatal Error] UnitMain.pas(21): F2063 Could not compile used unit 'Alcinoe.FMX.Layouts.pas'
> 
> use 11.3

This is standart behavior, when you forget to add Search Path in project options. You can see, how to use it in demo project AlFmxControls

**Comment by Magayver89** [comment]
Estou com o mesmo problema!
Alguma solução, ou somente alterando manualmente?

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
