### ISSUE TITLE
Build alcinoe-webrtc

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#286]
Build alcinoe-webrtc
d:\Install\Delphi\Alcinoe\Source\Java\com\alcinoe\webrtc\ALWebRTC.java:494: error: unmappable character (0x92) for encoding UTF-8
      // create a Capturer which takes the image/video from the device?s camera.
                                                                      ^
d:\Install\Delphi\Alcinoe\Source\Java\com\alcinoe\webrtc\ALWebRTC.java:895: error: unmappable character (0x97) for encoding UTF-8
      //including the media format. The method takes a single parameter?the session description?and it
                                                                       ^
d:\Install\Delphi\Alcinoe\Source\Java\com\alcinoe\webrtc\ALWebRTC.java:895: error: unmappable character (0x97) for encoding UTF-8
      //including the media format. The method takes a single parameter?the session description?and it
                                                                                               ^
3 errors

**Comment by Zeus64** [comment]
hello, when do you have such error ? when building the library with CompileJar.bat?
