### ISSUE TITLE
11.1 + 1.0.4

### ISSUE THREAD

**Issue by kazuser** [MagicFoundation/Alcinoe#287]
Hi there!

![image](https://user-images.githubusercontent.com/3335273/234048728-8b10bcc8-3dfa-4381-8a52-0c2c0f6291ec.png)

Could you please tell me how to fix it?

**Comment by kazuser** [comment]
![image](https://user-images.githubusercontent.com/3335273/234051697-cb5e5fc6-99fe-4901-ad27-f22205cd904a.png)

👌

**Comment by Zeus64** [comment]
hi, it's was because you don't have the alexandria 11.3 but probably the 11.2. you need the 11.3

**Comment by DiamatBR** [comment]
Hello again!
I tried running the ALFmxControls.
I'm using version 11.3.
Before it was giving the error "ChildrenMouseDown...".

I managed to get around it.
However, now this error appears:

![image](https://user-images.githubusercontent.com/77128586/236916717-af63128e-1f8a-4315-a745-204ae56ed17d.png)

**Comment by Zeus64** [comment]
it's look like you don't have alexandria 11.3 :(

**Comment by Zeus64** [comment]
with version of delphi are you exactly using ?

**Comment by DiamatBR** [comment]
![image](https://user-images.githubusercontent.com/77128586/236928853-0a4e1aeb-a816-4eb8-a7e1-af7db5f299ba.png)

**Comment by DiamatBR** [comment]
I was told that Delphi Community does not come with sources. Only the DCs. then it won't work
