### ISSUE TITLE
ScrollBoxes with TabControl

### ISSUE THREAD

**Issue by gonzzzales** [MagicFoundation/Alcinoe#289]
Hello!
I want to make this structure
    HorzScrollBox
  VertScrollBox
TabContlor

In tabs of TabControl i place VertScrollBoxes with Align  := Client, and in some VertScrollBoxes i place HorzScrollBox with some controls.
But unfortunetly i can`t swipe HorzScrollBox, TabControll intercepts my swipe. 
Is it possible to do it?
And one more question, i dont undestand, how work DeadZoneBeforeAcquireScrolling and can it help me?
Thanks a lot for answers!
Best regards.

**Comment by Zeus64** [comment]
DeadZoneBeforeAcquireScrolling have removed in the very last version
I do not think that TALTabContlor can contain VertScrollBoxes, i never tried but it's was not build for this.
