### ISSUE TITLE
Found fix for app that stalled on the splash screen

### ISSUE THREAD

**Issue by campbell-gary** [MagicFoundation/Alcinoe#290]
An app that contained only the ALMemo was stalling at the splash screen. 

The ALFmxControls (which ran without any problems on my phone) were loading the Libraries from here: 
..\Alcinoe\Demos\ALFmxControls\_Source\android\Merged\libs\64bit 

but the app I created (with only the ALMemo) was loading libraries from here:
C:\Program Files (x86)\Embarcadero\Studio\22.0\lib\android\debug 

So I disabled the Libraries and used the Libraries from ..\Alcinoe\Demos\ALFmxControls\_Source\android\Merged\libs\64bit 

Even though it now runs, there is a slight glitch with the magnifying glass showing too much text (when either the left or right selection points is pressed down)

**Comment by Zeus64** [comment]
hello, you must use a script like https://github.com/MagicFoundation/Alcinoe/blob/master/Demos/ALFmxControls/_Source/android/MergeLibraries.bat to include the libraries you need in you project. you must also include some res (like start icon, etc.) manually like it's done in https://github.com/MagicFoundation/Alcinoe/tree/master/Demos/ALFmxControls/_Source/android/App/res

**Comment by campbell-gary** [comment]
Thank you. I did a simple test on the ALMemo. The ALMemo has a property named DefStyleAttr which is set to BlueBGTextViewStyle. If the BlueBGTextViewStyle property is removed, and the app recompiled, the ALMemo "magnifying glass"  appears with a border shadow, and the highlighted text overlays the text on the line above it. 

When I set the DefStyleAttr property back to BlueBGTextViewStyle, then the "magnifying glass" effect works normally. The reason I experimented with this setting is because not all users would potentially want a blue background for their memo. Some users may prefer a white (or other color) background with black text.

**Comment by Zeus64** [comment]
to update the design of the ALmemo, under android it's work the same way as any other android app, you need to update the styles.xml. you can see an example here : https://github.com/MagicFoundation/Alcinoe/blob/master/Demos/ALFmxControls/_Source/android/App/res/values-v21/styles.xml

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
