### ISSUE TITLE
System.Net.HttpClient

### ISSUE THREAD

**Issue by kabiri** [MagicFoundation/Alcinoe#293]
When I add the System.Net.HttpClient unit to the program, this error occurs :
‍D:\Component\D11\alcinoe\Embarcadero\Alexandria\11_3\rtl\android\Androidapi.JNI.Android.Security.pas(90): error F2051: F2051 Unit System.Net.HttpClient.Android was compiled with a different version of Androidapi.JNIBridge.TJavaArray`1.GetItem

**Comment by Zeus64** [comment]
hello did you include in you search path https://github.com/MagicFoundation/Alcinoe/tree/master/Embarcadero/Alexandria/11_3 and all the sub paths ?

**Comment by kabiri** [comment]
Hello dear @Zeus64 
Yes.
$(alcinoe)\Source
$(alcinoe)\Embarcadero\Alexandria\11_3\fmx
$(alcinoe)\Embarcadero\Alexandria\11_3\rtl

**Comment by kabiri** [comment]
Thanks i add net dir and solved
