### ISSUE TITLE
Custom font for TALTExt 

### ISSUE THREAD

**Issue by gonzzzales** [MagicFoundation/Alcinoe#298]
I have found a problem with using custom font for TALText in Android. 
I made a font with icons for my app and use TALText and TLabel at the same time to display icons. With TLabel it is no problems, and TALText does not display the selected character.
With Windows and iOS it work fine, problem is only with Android.

**Comment by Zeus64** [comment]
hi @gonzzzales , can you make a little test, can you put on a form a TEdit with controlType= Plateform and see if your font work well ?

**Comment by gonzzzales** [comment]
hi @Zeus64, i made a test - it dont work. It work only, when i set controltype = Styled, and for TLabel too.

**Comment by Zeus64** [comment]
controlType=Styled mean it's FMX that draw everything. ControlType=Tlabel it's mean it's the OS that is responsible to draw the control. So it's look like that that os didn't have access to the font you just add, maybe you do something wrong in the way you add the font ?

**Comment by gonzzzales** [comment]
I think I have no problems with the font itself, since it is displayed correctly in ios with TALText, so the problem is only with android. I will check one more time.
If it possible, please try this font to use in android https://drive.google.com/file/d/1qo1Ef68QRA0fopG6noHjTkAZSfaE1c2p/view?usp=sharing

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version. You must use now the TALFontManager
