### ISSUE TITLE
 TAlMongoDBClient UpDateData

### ISSUE THREAD

**Issue by ViaCriativa** [MagicFoundation/Alcinoe#301]
Good morning,
Congratulations on Alcinoe.
How to perform an UpDateData with TAlMongoDBClient without losing the fields already inserted in an InsertData?

**Comment by ViaCriativa** [comment]
I found the solution:
include the **$Set** command in the Update field.

  aMongoDBClient.UpdateData('DB.CLIENTE',
                          '{_id: ObjectId("' + sID_Cli + '")}',
                          '{$set:{iCOD: 123456});
                          
Thanks! :)

**Comment by Zeus64** [comment]
happy you found the solution.
