### ISSUE TITLE
there is no bpl file on last version

### ISSUE THREAD

**Issue by AhmetNuri** [MagicFoundation/Alcinoe#302]
https://github.com/MagicFoundation/Alcinoe/tree/master/Libraries/obj/zlib/win64

there is no bpl file here and all the project

**Comment by Zeus64** [comment]
For security I do not provide anymore the BPL but no worry as you can generate it yourself by running [CompileJar.bat](https://github.com/MagicFoundation/Alcinoe/blob/master/CompileJar.bat)
