### ISSUE TITLE
Could you please make an installation video tutorial?

### ISSUE THREAD

**Issue by Tiagoadvir** [MagicFoundation/Alcinoe#303]
Please, would it be possible to record a video teaching how to install, because the part of compiling the unist, to replace the default ones, I cannot understand, I believe that like me there are other people with the same question. Thank you very much in advance.

**Comment by Zeus64** [comment]
Thank you for your feedback! I understand the need for clearer instructions. I've just updated the {alcinoe}\CompileAll.bat file. Now, you simply need to run this batch file to install everything correctly. Please ensure that you have Alexandria 11.3 installed for this to work smoothly. I hope this simplifies the process for you and others. If there are any other questions or concerns, feel free to ask!

**Comment by Tiagoadvir** [comment]
Thanks for your answer, when running compiler.bat I get the following return:
Compiler
--------

1) Alexandria
2) Sydney (obsolete)
Enter number to select a compiler (empty for automatic selection): 1

------------------
Delphi source code
------------------

Copy the Delphi source code and fix it locally (Y/N, default = Y)?:y

'E:\Components' is not recognized as an internal command
or external, an operable program or a batch file.
Press any key to continue. . .

**Comment by Zeus64** [comment]
Corrected, can you update your repository and launch again CompileALL.bat?

**Comment by Tiagoadvir** [comment]
Certainly...
--------
Compiler
--------

1) Alexandria
2) Sydney (obsolete)
Enter number to select a compiler (empty for automatic selection): 1

------------------
Delphi source code
------------------

Copy the Delphi source code and fix it locally (Y/N, default = Y)?:y

'"E:\Delphi Components\Delphi 11.3\ALCINOE\Alcinoe-master\\Embarcadero\Alexandria\Update.bat"' is not recognized as an internal command
or external, an operable program or a batch file.
Press any key to continue. . .

**Comment by Tiagoadvir** [comment]
'"E:\Componentes Delphi\Delphi 11.3\ALCINOE\Alcinoe-master\\Embarcadero\Alexandria\Update.bat"' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
Pressione qualquer tecla para continuar. . .

**Comment by Tiagoadvir** [comment]
certainly.. it is returning two slashes after alcinoeMaster \\ , I believe this is preventing the compiler....


Copy the Delphi source code and fix it locally (Y/N, default = Y)?:y

'"E:\Delphi Components\Delphi 11.3\ALCINOE\Alcinoe-master\ \Embarcadero\Alexandria\Update.bat"' is not recognized as an internal command
or external, an operable program or a batch file.
Press any key to continue. . .

**Comment by Zeus64** [comment]
strange with version of delphi do you have ?

normally 2 // doesn't matter in windows

**Comment by Tiagoadvir** [comment]
the vertion is 11.3

**Comment by Zeus64** [comment]
and windows ?

**Comment by Tiagoadvir** [comment]
its Microsoft Windows [versão 10.0.17763.4851]

**Comment by Tiagoadvir** [comment]
I think I have more or less found it,
The script looks inside the folder: Alcinoe-master\Embarcadero\Alexandria, for the Update.bat file, however there are still two subfolders inside the alexandria folder, which are 11.2 and 11.3, when removing to the root "Alexandria" it passed the first step, but now return to the following reason:
Download https://github.com/facebook/facebook-ios-sdk/releases/download/v15.1.0/FacebookSDK-Static_XCFramework.zip
    % Total % Received % Xferd Average Speed Time Time Current Time
                                   Dload Upload Total Spent Speed Left
    0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check for certificate revocation.
Press any key to continue. . .

**Comment by Zeus64** [comment]
Is everything working now? can i close this ticket ?

**Comment by Tiagoadvir** [comment]
Hello, yes, it works well, you can close it, and I am very grateful for the help and patience you had in helping me. And correct the compileall.bat file, which hasn't run for days.
