### ISSUE TITLE
Error with Choreographer

### ISSUE THREAD

**Issue by helgovic** [MagicFoundation/Alcinoe#304]
On app launch i get this error:

09-22 04:54:35.253 14032 14505 W System.err: java.lang.IllegalStateException: The current thread must have a looper!
09-22 04:54:35.253 14032 14505 W System.err: 	at android.view.Choreographer$1.initialValue(Choreographer.java:116)
09-22 04:54:35.254 14032 14505 W System.err: 	at android.view.Choreographer$1.initialValue(Choreographer.java:111)
09-22 04:54:35.254 14032 14505 W System.err: 	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
09-22 04:54:35.254 14032 14505 W System.err: 	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
09-22 04:54:35.254 14032 14505 W System.err: 	at android.view.Choreographer.getInstance(Choreographer.java:319)
09-22 04:54:35.254 14032 14505 W System.err: 	at com.embarcadero.rtl.ProxyInterface.dispatchToNative2(Native Method)
09-22 04:54:35.254 14032 14505 W System.err: 	at com.embarcadero.rtl.ProxyInterface.invoke(ProxyInterface.java:20)
09-22 04:54:35.254 14032 14505 W System.err: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
09-22 04:54:35.254 14032 14505 W System.err: 	at $Proxy25.onQueryPurchasesResponse(Unknown Source)
09-22 04:54:35.254 14032 14505 W System.err: 	at com.android.billingclient.api.zzy.call(com.android.billingclient:billing@@6.0.1:2)
09-22 04:54:35.254 14032 14505 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-22 04:54:35.254 14032 14505 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-22 04:54:35.254 14032 14505 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-22 04:54:35.254 14032 14505 W System.err: 	at java.lang.Thread.run(Thread.java:1012)

**Comment by Zeus64** [comment]
With app ? it's in one of the demo ?

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
