### ISSUE TITLE
Dontcompile whit some components alcinoe

### ISSUE THREAD

**Issue by Tiagoadvir** [MagicFoundation/Alcinoe#305]
![image](https://github.com/MagicFoundation/Alcinoe/assets/11960978/edce3a1b-7102-43a7-9e44-7588432700ee)

When I use Layout or TAmemo, TAEdits... I get these restrictions, I don't know if it's the component or an error on my machine. I reinstalled Alcinoe, according to the guidelines and latest corrections...

**Comment by Tiagoadvir** [comment]
![image](https://github.com/MagicFoundation/Alcinoe/assets/11960978/3a581e10-7c8e-4031-962f-92ed05108fa0)
Sorry once again, I'm having problems, I thought I had solved it for the last time, but I see that you are not patching the files to be able to use the visual components.

**Comment by Zeus64** [comment]
Hello, Can you Investigate in your computer why the command "call .\InitEnvironment.bat" located in CompileAll.bat didn't work ?
My guess is that you call CompileAll.bat from a directory different than the Alcinoe root dir

**Comment by Zeus64** [comment]
look to it's corrected, if you can try again and confirm everything work as expected ?

**Comment by Tiagoadvir** [comment]
Im try againg, aparentely its work well, thanks.
