### ISSUE TITLE
Can´t compile

### ISSUE THREAD

**Issue by DesenvolvimentoOazez** [MagicFoundation/Alcinoe#307]
CompileAll.bat ...

MSBuild ALTests.dproj /p:config=Debug /p:Platform=Win32
Microsoft (R) Versão do Mecanismo de Compilação 4.8.9032.0
[Microsoft .NET Framework, Versão 4.0.30319.42000]
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

  Embarcadero Delphi for Win32 compiler version 35.0
  Copyright (c) 1983,2021 Embarcadero Technologies, Inc.
C:\Projects\Componentes\Alcinoe\Source\Alcinoe.FMX.Layouts.pas(50): error E2137: Method 'IsVisibleObject' not fou
nd in base class [C:\Projects\Componentes\Alcinoe\Tests\_Source\ALTests.dproj]
C:\Projects\Componentes\Alcinoe\Source\Alcinoe.FMX.Layouts.pas(144): error E2137: Method 'ChildrenMouseDown' not
found in base class [C:\Projects\Componentes\Alcinoe\Tests\_Source\ALTests.dproj]
C:\Projects\Componentes\Alcinoe\Source\Alcinoe.FMX.Layouts.pas(145): error E2137: Method 'ChildrenMouseMove' not
found in base class [C:\Projects\Componentes\Alcinoe\Tests\_Source\ALTests.dproj]
C:\Projects\Componentes\Alcinoe\Source\Alcinoe.FMX.Layouts.pas(146): error E2137: Method 'ChildrenMouseUp' not fo
und in base class [C:\Projects\Componentes\Alcinoe\Tests\_Source\ALTests.dproj]
C:\Projects\Componentes\Alcinoe\Source\Alcinoe.FMX.Layouts.pas(147): error E2137: Method 'ChildrenMouseLeave' not
 found in base class [C:\Projects\Componentes\Alcinoe\Tests\_Source\ALTests.dproj]
ALTests.dpr(195): error F2063: Could not compile used unit 'Alcinoe.FMX.Layouts.pas' [C:\Projects\Componentes\Alc
inoe\Tests\_Source\ALTests.dproj]

**Comment by Zeus64** [comment]
it's because you do not have Embarcadero Alexandria 11.3 (the very last). you need the very last version of embarcadero with the source code to be able to run the compileAll.bat
