### ISSUE TITLE
MORE is not recognized

### ISSUE THREAD

**Issue by Tiagoadvir** [MagicFoundation/Alcinoe#308]
![image](https://github.com/MagicFoundation/Alcinoe/assets/11960978/2b0bc515-a28f-451f-acce-c3421478bd5f)

When choosing option two for compilation, I am receiving the error as shown in the image, which says: "MORE is not recognized as an internal command.

**Comment by halebahay** [comment]
run Compileall.bat as administrator

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
