### ISSUE TITLE
Error installing Delphi 11 CE

### ISSUE THREAD

**Issue by Magayver89** [MagicFoundation/Alcinoe#311]
**Alcinoe v1.0.7**

[dcc32 Error] Alcinoe.FMX.Layouts.pas(60): E2137 Method 'IsVisibleObject' not found in base class
[dcc32 Error] Alcinoe.FMX.Layouts.pas(154): E2137 Method 'ChildrenMouseDown' not found in base class
[dcc32 Error] Alcinoe.FMX.Layouts.pas(155): E2137 Method 'ChildrenMouseMove' not found in base class
[dcc32 Error] Alcinoe.FMX.Layouts.pas(156): E2137 Method 'ChildrenMouseUp' not found in base class
[dcc32 Error] Alcinoe.FMX.Layouts.pas(157): E2137 Method 'ChildrenMouseLeave' not found in base class
[dcc32 Fatal Error] Alcinoe.FMX.TabControl.pas(78): F2063 Could not compile used unit 'Alcinoe.FMX.Layouts.pas'

*************************************************************************************************************************
Copy the Delphi source code and patch it locally (Y/N, default=Y)?: Y

Copy "C:\Program Files (x86)\Embarcadero\Studio\22.0\source\fmx"
251 arquivo(s) copiado(s)
Copy "C:\Program Files (x86)\Embarcadero\Studio\22.0\source\rtl\ios"
0 arquivo(s) copiado(s)
Copy "C:\Program Files (x86)\Embarcadero\Studio\22.0\source\rtl\osx"
119 arquivo(s) copiado(s)
Copy "C:\Program Files (x86)\Embarcadero\Studio\22.0\source\rtl\android"
72 arquivo(s) copiado(s)
Copy "C:\Program Files (x86)\Embarcadero\Studio\22.0\source\rtl\win"
134 arquivo(s) copiado(s)
Copy "C:\Program Files (x86)\Embarcadero\Studio\22.0\source\rtl\net"
22 arquivo(s) copiado(s)
Patch the locally copied source code
Checking patch Embarcadero/Alexandria/fmx/FMX.Canvas.D2D.pas...
Hunk #1 succeeded at 2898 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.Canvas.GPU.Helpers.pas...
Hunk #1 succeeded at 16 (offset 1 line).
Hunk #2 succeeded at 314 (offset 1 line).
Hunk #3 succeeded at 427 (offset 1 line).
Hunk #4 succeeded at 437 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.Canvas.GPU.pas...
Hunk #1 succeeded at 73 (offset 1 line).
Hunk #2 succeeded at 1215 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.Context.GLES.pas...
Hunk #1 succeeded at 189 (offset 1 line).
Hunk #2 succeeded at 1313 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.Controls.pas...
Hunk #1 succeeded at 116 (offset 1 line).
Hunk #2 succeeded at 516 (offset 1 line).
Hunk #3 succeeded at 608 (offset 1 line).
Hunk #4 succeeded at 2227 (offset 1 line).
Hunk #5 succeeded at 2234 (offset 1 line).
Hunk #6 succeeded at 2277 (offset 1 line).
Hunk #7 succeeded at 2308 (offset 1 line).
Hunk #8 succeeded at 2396 (offset 1 line).
Hunk #9 succeeded at 2468 (offset 1 line).
Hunk #10 succeeded at 2505 (offset 1 line).
Hunk #11 succeeded at 2957 (offset 1 line).
Hunk #12 succeeded at 3423 (offset 1 line).
Hunk #13 succeeded at 3466 (offset 1 line).
Hunk #14 succeeded at 3688 (offset 1 line).
Hunk #15 succeeded at 3706 (offset 1 line).
Hunk #16 succeeded at 3965 (offset 1 line).
Hunk #17 succeeded at 4154 (offset 1 line).
Hunk #18 succeeded at 4164 (offset 1 line).
Hunk #19 succeeded at 4456 (offset 1 line).
Hunk #20 succeeded at 4581 (offset 1 line).
Hunk #21 succeeded at 4604 (offset 1 line).
Hunk #22 succeeded at 4613 (offset 1 line).
Hunk #23 succeeded at 4628 (offset 1 line).
Hunk #24 succeeded at 6085 (offset 1 line).
Hunk #25 succeeded at 7243 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.Filter.pas...
Hunk #1 succeeded at 608 (offset 1 line).
Hunk #2 succeeded at 839 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.Forms.pas...
Hunk #1 succeeded at 4375 (offset 1 line).
Hunk #2 succeeded at 4855 (offset 1 line).
Hunk #3 succeeded at 5635 (offset 1 line).
Hunk #4 succeeded at 5932 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.Platform.iOS.pas...
error: Embarcadero/Alexandria/fmx/FMX.Platform.iOS.pas: No such file or directory
Checking patch Embarcadero/Alexandria/fmx/FMX.Platform.Screen.Android.pas...
Hunk #1 succeeded at 259 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.Platform.UI.Android.pas...
Hunk #1 succeeded at 27 (offset 1 line).
Hunk #2 succeeded at 42 (offset 1 line).
Hunk #3 succeeded at 1160 (offset 1 line).
Hunk #4 succeeded at 1334 (offset 1 line).
Hunk #5 succeeded at 2779 (offset 1 line).
Hunk #6 succeeded at 2789 (offset 1 line).
Hunk #7 succeeded at 2797 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.Presentation.Android.Style.pas...
Hunk #1 succeeded at 72 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.StrokeBuilder.pas...
Hunk #1 succeeded at 89 (offset 1 line).
Hunk #2 succeeded at 99 (offset 1 line).
Hunk #3 succeeded at 923 (offset 1 line).
Hunk #4 succeeded at 1077 (offset 1 line).
Checking patch Embarcadero/Alexandria/fmx/FMX.VirtualKeyboard.Android.pas...
Hunk #1 succeeded at 219 (offset 1 line).
Checking patch Embarcadero/Alexandria/rtl/android/Androidapi.JNI.App.pas...
Hunk #1 succeeded at 17 (offset 1 line).
Hunk #2 succeeded at 78 (offset 1 line).
Hunk #3 succeeded at 1485 (offset 1 line).
Hunk #4 succeeded at 1569 (offset 1 line).
Hunk #5 succeeded at 1829 (offset 1 line).
Hunk #6 succeeded at 2292 (offset 1 line).
Checking patch Embarcadero/Alexandria/rtl/android/Androidapi.JNI.Location.pas...
Hunk #1 succeeded at 583 (offset 1 line).
Hunk #2 succeeded at 595 (offset 1 line).
Hunk #3 succeeded at 605 (offset 1 line).
Checking patch Embarcadero/Alexandria/rtl/ios/iOSapi.AVFoundation.pas...
error: Embarcadero/Alexandria/rtl/ios/iOSapi.AVFoundation.pas: No such file or directory
Checking patch Embarcadero/Alexandria/rtl/ios/iOSapi.CoreImage.pas...
error: Embarcadero/Alexandria/rtl/ios/iOSapi.CoreImage.pas: No such file or directory
Checking patch Embarcadero/Alexandria/rtl/ios/iOSapi.CoreLocation.pas...
error: Embarcadero/Alexandria/rtl/ios/iOSapi.CoreLocation.pas: No such file or directory
Checking patch Embarcadero/Alexandria/rtl/ios/iOSapi.Foundation.pas...
error: Embarcadero/Alexandria/rtl/ios/iOSapi.Foundation.pas: No such file or directory
Checking patch Embarcadero/Alexandria/rtl/ios/iOSapi.Security.pas...
error: Embarcadero/Alexandria/rtl/ios/iOSapi.Security.pas: No such file or directory
Checking patch Embarcadero/Alexandria/rtl/ios/iOSapi.UIKit.pas...
error: Embarcadero/Alexandria/rtl/ios/iOSapi.UIKit.pas: No such file or directory
Checking patch Embarcadero/Alexandria/rtl/win/Winapi.Isapi2.pas...
Hunk #1 succeeded at 398 (offset 1 line).
Remove warnings from the copied files
Delphi source code has been copied and patched successfully

**Comment by Zeus64** [comment]
please try with delphi 12 (Athens)

**Comment by okbach** [comment]
Make sure you have git installed
