### ISSUE TITLE
TEdit in TALVertScrollBox (Android)

### ISSUE THREAD

**Issue by cfusari** [MagicFoundation/Alcinoe#314]
Hi, I have an issue since ScrollEngine has replaced AniCalculations.
Using Delphi 11.3 or 12, Android

If I put a TEdit inside a ALVertScroll, I need to double tap to give it focus and edition and keyboard.
The simple tap is silent. A TEdit in a Delphi VertScroll is responding to single tap as it was responding in older version of ALVertScroll.
I tried to find where it is without success.

Best regards

**Comment by Zeus64** [comment]
hi cfusari, can you try to run the demo https://github.com/MagicFoundation/Alcinoe/tree/master/Demos/ALFmxControls/_Source to see if the problem is still here? at the bottom of the scrollbox their is an edit and a memo

**Comment by cfusari** [comment]
Hi, yes I tried, but I have an error while linking: (it was working long time ago (Delphi 10 I think))
[DCC Erreur] E2597: In function `__cxa_get_globals': undefined reference to `__emutls_get_address'
In function `__cxa_get_globals_fast': undefined reference to `__emutls_get_address'
I am using NDK 22.1.7171670 which is working for my projects.

**Comment by Zeus64** [comment]
I think NDK 22 is not compatible, you must avoid it.
try the sdk you can find here: https://github.com/MagicFoundation/PlatformSDKs.git
more info about using another SDK than the one provided : https://stackoverflow.com/questions/60084704/aab-format-return-an-apk-without-armeabi-v7a-library-under-32-bit-devices

**Comment by cfusari** [comment]
I download and I will try.

**Comment by cfusari** [comment]
Hi, ok, TALEdit is working, I put a TEdit in the demo, it is not working.

**Comment by Zeus64** [comment]
do you use TEdit in native style or firemonkey style ?

**Comment by cfusari** [comment]
I use Styled (I took the item and drop without modification)
I tried Platform, it is working.

**Comment by cfusari** [comment]
ok, I will do the same. Thanks
