### ISSUE TITLE
Delphi 11.2 cannot compile ： FMessageId: TMessageSubscriptionId;

### ISSUE THREAD

**Issue by chenzhifeng0025** [MagicFoundation/Alcinoe#315]
[dcc32 Error] FMX.TextLayout.pas(69): E2003 Undeclared identifier: 'TMessageSubscriptionId'

**Comment by Zeus64** [comment]
the master branch is only compatible with Athens (delphi 12). if you need to work with Alexandria you must use this : https://github.com/MagicFoundation/Alcinoe/releases/tag/v1.0.7
