### ISSUE TITLE
CompileAll.bat is not passing

### ISSUE THREAD

**Issue by stuxamber** [MagicFoundation/Alcinoe#317]
`Build Jars (Y/N, default=Y)?:

FMXJAR=C:\Program Files (x86)\Embarcadero\Studio\23.0\lib\android\release\fmx.jar
PlatformSDK=AndroidSDK25.2.5_64bit.sdk
SDKApiLevelPath=C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidSDK-2525-23.0.50491.5718\platforms\android-33
JDKBinPath="C:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot\\bin"

Build alcinoe-common
C:\Users\stux\Downloads\Alcinoe-master\Source\Java\com\alcinoe\util\ALFileUtil.java:7: error: package android.content does not exist
import android.content.Context;
                      ^
C:\Users\stux\Downloads\Alcinoe-master\Source\Java\com\alcinoe\util\ALFileUtil.java:8: error: package android.net does not exist
import android.net.Uri;`

and many more errors.

How do I get pass this?

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
