### ISSUE TITLE
[dcc32 Error] Alcinoe.FMX.BreakText.pas(4189): E2034 Too many actual parameters

### ISSUE THREAD

**Issue by marlonnardi** [MagicFoundation/Alcinoe#319]
CompileAll.bat -> Executed

![image](https://github.com/MagicFoundation/Alcinoe/assets/5359931/8ef35336-106c-4179-8b1d-ea534b6d69b9)

**Comment by Zeus64** [comment]
hello [marlonnardi](https://github.com/marlonnardi), are you on the master or on the "skia" branch ?

**Comment by marlonnardi** [comment]
I tested on both, both have the same problem, each in their compilation directive.

**Comment by marlonnardi** [comment]
> hello [marlonnardi](https://github.com/marlonnardi), are you on the master or on the "skia" branch ?

resolved to use the master branch with the last update yesterday (15/02)
![image](https://github.com/MagicFoundation/Alcinoe/assets/5359931/95333f1b-73c0-4cf1-b658-c128595eab54)

**Comment by Zeus64** [comment]
the skia is not yet finished, still in progress. hope to be ready soon
