### ISSUE TITLE
Delphi Athens - Method 'IsVisibleObject' not found in base class

### ISSUE THREAD

**Issue by MarcioDe** [MagicFoundation/Alcinoe#320]
---------------------
Build ALTests Project
---------------------

Could Not Find D:\Alcinoe-master\Tests\*.identcache
Could Not Find D:\Alcinoe-master\Tests\*.dproj.local
Could Not Find D:\Alcinoe-master\Tests\*.groupproj.local
Could Not Find D:\Alcinoe-master\Tests\*.deployproj.local

MSBuild ALTests.dproj /p:config=Debug /p:Platform=Win32
Microsoft (R) Build Engine w wersji 4.8.9032.0
[Microsoft .NET Framework w wersji 4.0.30319.42000]
Copyright (C) Microsoft Corporation. Wszelkie prawa zastrzeżone.

  Embarcadero Delphi for Win32 compiler version 36.0
  Copyright (c) 1983,2023 Embarcadero Technologies, Inc.
D:\Alcinoe-master\Source\Alcinoe.FMX.Layouts.pas(60): error E2137: Method 'IsVisibleObject' not found in base class [D:
\Alcinoe-master\Tests\_Source\ALTests.dproj]
D:\Alcinoe-master\Source\Alcinoe.FMX.Layouts.pas(154): error E2137: Method 'ChildrenMouseDown' not found in base class
[D:\Alcinoe-master\Tests\_Source\ALTests.dproj]
D:\Alcinoe-master\Source\Alcinoe.FMX.Layouts.pas(155): error E2137: Method 'ChildrenMouseMove' not found in base class
[D:\Alcinoe-master\Tests\_Source\ALTests.dproj]
D:\Alcinoe-master\Source\Alcinoe.FMX.Layouts.pas(156): error E2137: Method 'ChildrenMouseUp' not found in base class [D
:\Alcinoe-master\Tests\_Source\ALTests.dproj]
D:\Alcinoe-master\Source\Alcinoe.FMX.Layouts.pas(157): error E2137: Method 'ChildrenMouseLeave' not found in base class
 [D:\Alcinoe-master\Tests\_Source\ALTests.dproj]
ALTests.dpr(193): error F2063: Could not compile used unit 'Alcinoe.FMX.Layouts.pas' [D:\Alcinoe-master\Tests\_Source\A
LTests.dproj]
Press any key to continue . . .

**Comment by MarcioDe** [comment]
How to solve this error from appearing?

**Comment by Zeus64** [comment]
Hello, you need to use delphi 12 athens with source code included. with version of delphi 12 athens do you have ?

**Comment by MarcioDe** [comment]
In the footer of the email from github.com with this message from you "Hello, you need to use delphi 12 athens with source code included. with version of delphi 12 athens do you have ?" it says:
Reply to this email directly, view it on GitHub, or unsubscribe.
So I replied directly.
How can I send you my recorded desktop?

**Comment by MarcioDe** [comment]
Please let me know if I'm doing something wrong.
Here is a video showing what I do:
https://www.marmedia.net.pl/tmp/video1.mp4
Now I have downloaded "Alcinoe-master" and Delphi 12 (Athens) is available, but exactly the same thing is happening as in the recorded video.

**Comment by Zeus64** [comment]
@MarcioDe it's look like you do not have git for windows installed on your machine. you need it, I use it to merge the delphi source code ( https://gitforwindows.org/ or any other git client you want )

**Comment by MarcioDe** [comment]
Thank you :-)))
It's very, very good because the **video** works wonderfully on Android and iOS :-)
Unfortunately, it does not work on Windows 32/64 bit and macOS 64-bit.
What could be the reason?

**Comment by Zeus64** [comment]
because it's not yet implemented on windows :( I need it only for ios/android right now. if someone want to implement it on windows would be great :)

**Comment by MarcioDe** [comment]
Hello. I added movie playback (also HLS) for Windows 32/64 bit to the "ALFmxControls" project :)
Zeus64, write to me at the following e-mail address: zeus64@marmedia.net.pl and I will reply to you with details of what I changed and what files should be added.
This is a small amount of code.
