### ISSUE TITLE
Delphi 11 - Android - attr/lStar not found

### ISSUE THREAD

**Issue by duzzell** [MagicFoundation/Alcinoe#322]
Hello

I'm using Delphi 11.0. I'd like to use the Alcinoe Android edit control. I've installed Alcinoe. I think I need to run MergeLibraries.bat. When I run the version from ALFMXControls I get an error:

`error: resource android:attr/lStar not found.`

After some searching, one solution seems to be changing my maxTargetSdkVersion in Delphi from 30 to 31. Since the maxTargetSdkVersion is set by Embarcadero, I hesitate to try that. 

A second solution seems to be editing my build.gradle file. None of the edits below has helped.

I'd appreciate any help on clearing this error. 

Thanks

*****************************
build.gradle edits

*****************************
//no fix
```
configurations.all {
    resolutionStrategy {
        force 'androidx.core:core-ktx:1.6.0'
    }
}
```

********************************
//can't find method 'implementation'
```
dependencies {
    implementation "androidx.core:core-ktx:1.6.0"
}
```

**********************************
//no fix
```
android {
    configurations.all {
        resolutionStrategy {
            force 'androidx.appcompat:appcompat:1.3.0'
            force 'androidx.core:core-ktx:1.6.0'
        }
    }
}

dependencies {
    implementation "androidx.core:core-ktx:1.6.0"
    implementation "androidx.appcompat:appcompat:1.3.0"
}
```

*********************************************
//no fix
```
buildscript {
    repositories {
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
    }
}
```

********************************
//no fix
```
ext {
    androidXCore = "1.6.0"
}
```

************************

**Comment by Zeus64** [comment]
Hi, can you check the version of java you are using ? if you are using the Delphi 11 (alexandria) you must take this version: 
https://github.com/MagicFoundation/Alcinoe/releases/tag/v1.0.7

this is for exemple the java version I use : 

openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
