### ISSUE TITLE
access violation at address 04DB31CD ACCESSING ADRESS 00000000

### ISSUE THREAD

**Issue by Eaglemaster31** [MagicFoundation/Alcinoe#323]
Hello Mr  Zeus64  please help. 

I am using Alcinoe's video player on delphi 12  it compile with no error but when app is run it show error 

access violation at address 04DB31CD ACCESSING ADRESS 00000000

  I added all the exoplayer .jar files.

![Sans titre](https://github.com/MagicFoundation/Alcinoe/assets/50497007/8af7fabf-626c-46b4-9ccb-7d7449cc833f)

**Comment by Zeus64** [comment]
hello, can you try the ALFMXControls demo and say me if you encounter the same error in the demo ?

**Comment by Eaglemaster31** [comment]
Thank's for replay ,Yes I test ALFMXControls demo and error with ALFmxTabControl.pas Method 'ChildrenMouseDown' not found in base class  I remove all things related with allayout and build app when run it hung  and not show main form maybe the problem is in the manifest add some thing like package i don't knew  this is my project 
[4.zip](https://github.com/MagicFoundation/Alcinoe/files/14736305/4.zip)
in delphi 12 archi
![Sans titre](https://github.com/MagicFoundation/Alcinoe/assets/50497007/0f7c109d-565c-4415-822c-3e5a4f1ac280)

**Comment by gonzzzales** [comment]
You must add in your project options -> delphi compiller - Search Path correct path to alcinoe. Something like this
D:\Alcinoe-master\Embarcadero\Athens\fmx
D:\Alcinoe-master\Embarcadero\Athens\rtl\android
D:\Alcinoe-master\Source
(this is for Android)

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
