### ISSUE TITLE
RADStudio_12_1

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#324]
https://altd.embarcadero.com/download/radstudio/12.0/RADStudio_12_1_esd_61_7529b.exe
https://altd.embarcadero.com/download/radstudio/12.0/RADStudio_12_1_61_7529.iso
Should I wait for support?

**Comment by MarcioDe** [comment]
I join the question.

**Comment by Zeus64** [comment]
Hello, I m actively working on it :) The next release will also have the full SKIA support and some other evolutions

**Comment by Spelt** [comment]
Sounds just awesome!Op 2 apr 2024 om 17:01 heeft Zeus64 ***@***.***> het volgende geschreven:﻿
Hello, I m actively working on it :) The next release will also have the full SKIA support and some other evolutions

**Comment by firemen01** [comment]
at least in terms of timing? )

_https://altd.embarcadero.com/getit/public/libraries/Patches/R121.patch1-20240416-2.zip

**Comment by firemen01** [comment]
gentlemen bourgeois! please help the author with money. Unfortunately, I am from a sanctioned region, so I would be happy to help with the development of the project. Give someone as much as you can - it definitely won’t hurt him..

**Comment by Zeus64** [comment]
thanks @firemen01 :) I m actively working on it, it's take me much time that i was originally thinking. Actually i m still on the skia migration, and I work on it every days! I hope to finish in the next 1 or 2 week. This skia migration take me too much time honestly i will take some conclusion when i will finish it

**Comment by ChristenTematica** [comment]
Interested in this evolution

**Comment by SerhatYanalak** [comment]
Hello, Dear friend. Will a new version be released for Delphi 12.1, or does everything work flawlessly in the current Delphi 12.1 version?

**Comment by Zeus64** [comment]
Athens 12.2 is now available on the master branch. Please give it a try.

I also have an online demo available at [this link](https://play.google.com/apps/internaltest/4701314002613599109), and I need 20 internal testers to make it public. If you're able to help, please send me your email so I can add you to the tester list.

Thanks for your support!
