### ISSUE TITLE
CompileJar.bat

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#327]
I wrote earlier, but it remained unanswered,
I just keep running into an error in CompileJar.bat

FOR /F "usebackq tokens=3*" %%A IN (`reg query "HKCU\Software\Embarcadero\BDS\%ALDelphiVersion%\PlatformSDKs\%PlatformSDK%" /v JDKPath`) DO set JDKPath=%%A % %B

why is there a space between %%A %%B ? I get as a result:
JDKBinPath="d:\Install\Android\JDKHotspot\ \bin"

then an error appears along the way...

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
