### ISSUE TITLE
Alcinoe [Master] Binary Compatibility in Delphi 12 and 12.1

### ISSUE THREAD

**Issue by Elinulok32** [MagicFoundation/Alcinoe#328]
In Delphi Alexandria, Release 11.1 was binary compatible with 11, and so was release 11.2 and 11.3. I don't know if the same applies to Athens 12 and 12.1. 

Please, my question is, **is it possible to use the current version of Alcinoe Master (not Alcinoe SKIA) with Delphi 12.1?** 
If not, can we get a Delphi 12.1 compatible version. I know you're working hard to release it with support for SKIA, but while SKIA support is not yet ready, we would appreciate it, if a compatible version is made for delphi 12.1 while we wait for SKIA support so that we can successfully recompile our existing app for our clients with the new features in Delphi 12.1. 

Thank you.

**Comment by firemen01** [comment]
It works fine for me,

**Comment by Elinulok32** [comment]
It worked fine for me too. Thanks
I only have a couple of issues. I used "TALVertScrollBox.AniCalculations.BoundsAnimation := False;" in 11.3 now I'm using 12.1 and I'm getting an error. I tried with "TALVertScrollBox.ScrollEngine...." but found no way to set BoundsAnimation. Any assistance please.

**Comment by Elinulok32** [comment]
> It works fine for me,

It worked fine for me too. Thanks
I only have a couple of issues. I used "TALVertScrollBox.AniCalculations.BoundsAnimation := False;" in 11.3 now I'm using 12.1 and I'm getting an error. I tried with "TALVertScrollBox.ScrollEngine...." but found no way to set BoundsAnimation. Any assistance please.
