### ISSUE TITLE
Delphi 12 Replacement for TALVertScrollBox.AniCalculations.BoundsAnimation

### ISSUE THREAD

**Issue by Elinulok32** [MagicFoundation/Alcinoe#329]
Hello, how do I prevent the edges of the Alcinoe scrollboxes from springing back in delphi 12, like we used to do in Alexendria 11.3 with AniCalculations.BoundsAnimation. I tried TALVertScrollBox.ScrollEngine.MinEdgeSpringbackEnabled := False; and TALVertScrollBox.ScrollEngine.MaxEdgeSpringbackEnabled := False; but it did not work. Please your help is urgently needed.

**Comment by Zeus64** [comment]
hi normaly MinEdgeSpringbackEnabled and MaxEdgeSpringbackEnabled must do the job, can you send me a demo project just i can see what wrong ?

**Comment by Elinulok32** [comment]
[MultiDeviceTests.zip](https://github.com/user-attachments/files/15753883/MultiDeviceTests.zip)

**Comment by Elinulok32** [comment]
> hi normaly MinEdgeSpringbackEnabled and MaxEdgeSpringbackEnabled must do the job, can you send me a demo project just i can see what wrong ?

Hello @Zeus64, please I've sent you the demo you requested for and it's been 3 days now. I know you're very busy but kindly check it up and revert soon. Thanks

**Comment by Elinulok32** [comment]
Hello, thanks for getting back soon. The second option worked fine for me. I'm very grateful.
