### ISSUE TITLE
Any idea when the Alcinoe+Skia project will be "ready"?

### ISSUE THREAD

**Issue by marlonnardi** [MagicFoundation/Alcinoe#331]
Hi @Zeus64 , do you have any idea when the Alcinoe+Skia project will be "ready"?
I'm looking forward to it.

For each branch you upload I do a new test to see if it works :)

![image](https://github.com/user-attachments/assets/7112ff9d-d9da-41ad-8d47-7485191e3e4d)

![image](https://github.com/user-attachments/assets/04a3490b-89a1-40c6-b556-08f1a8f4d59f)

**Comment by marlonnardi** [comment]
My main focus would be this wonder here, TALEdit and TALMemo

![image](https://github.com/user-attachments/assets/86d5f1c8-26ad-4244-9822-c8163fd0a116)

**Comment by marlonnardi** [comment]
I don't know how to send you a private message @Zeus64, but here's my email marlon.nardi@gmail.com

**Comment by Zeus64** [comment]
Finally I think I do not need your email. Can you try to install the Alcinoe Firemonkey controls demo app: https://play.google.com/apps/internaltest/4701218363717235793 and say me what you think about it ?

**Comment by Zeus64** [comment]
Note: If you'd like to try the demo, please send me your email so I can invite you. Due to new Google Play rules, I need at least 14 testers to make the demo public. :)

**Comment by OnePeople-source** [comment]
@Zeus64, hi, can i test the demo?

**Comment by Zeus64** [comment]
@OnePeople-source can you send me your android google account email, i will add it to the list

**Comment by OnePeople-source** [comment]
***@***.***
--
Отправлено из Mail.ru для Android вторник, 20 августа 2024г., 18:01 +07:00 от Zeus64  ***@***.*** :

**Comment by Zeus64** [comment]
@OnePeople-source I didn't received your email :(

**Comment by OnePeople-source** [comment]
I have it sent. Here is my email ***@***.***
--
Отправлено из Mail.ru для Android вторник, 20 августа 2024г., 19:03 +07:00 от Zeus64  ***@***.*** :

**Comment by OnePeople-source** [comment]
I have it sent. Here is my email volodiadantew@gmail.com

**Comment by Zeus64** [comment]
I just add you to the list, can you try the demo here now : https://play.google.com/apps/internaltest/4701218363717235793
Say me what you think about it

**Comment by OnePeople-source** [comment]
> I just add you to the list, can you try the demo here now : https://play.google.com/apps/internaltest/4701218363717235793 Say me what you think about it

Hi. I tried the demo and I have a question, in the demo scrollbox delphi controls, delphi controls use what rendering? After all, skia should draw the same as alcinoe in quality, and the smoothness should not be so deoghan!? And also the rendering performance is of course good, but what to do with creating a list of 10,000 controls, your library really lacks a fast listvew or better containerview (tlistbox delphi) only with fast component creation and smooth scrolling. Thanks in advance.

**Comment by Zeus64** [comment]
> > I just add you to the list, can you try the demo here now : https://play.google.com/apps/internaltest/4701218363717235793 Say me what you think about it
> 
> Hi. I tried the demo and I have a question, in the demo scrollbox delphi controls, delphi controls use what rendering? After all, skia should draw the same as alcinoe in quality, and the smoothness should not be so deoghan!? And also the rendering performance is of course good, but what to do with creating a list of 10,000 controls, your library really lacks a fast listvew or better containerview (tlistbox delphi) only with fast component creation and smooth scrolling. Thanks in advance.


If you want to create a TListBox with 10,000 controls, it will never (never) be fast. You simply can't do that. You need to understand that every time you move the scrollbox of the TListBox by one pixel, you're also moving the position of all 10,000 controls.

To achieve this, you should create each control on the fly (and destroy them on the fly as well) so that the listbox only contains a few controls at any given time.

That's what we do in this app: https://www.youtube.com/watch?v=IJzEuZTSXDI&vq=hd2160

As for Skia, it's faster than CanvasGPU, but it's not magic either. :)

**Comment by marlonnardi** [comment]
> My main focus would be this wonder here, TALEdit and TALMemo
> 
> ![image](https://private-user-images.githubusercontent.com/5359931/356060570-86d5f1c8-26ad-4244-9822-c8163fd0a116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzEzNDMsIm5iZiI6MTcyNjU3MTA0MywicGF0aCI6Ii81MzU5OTMxLzM1NjA2MDU3MC04NmQ1ZjFjOC0yNmFkLTQyNDQtOTgyMi1jODE2M2ZkMGExMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTdUMTEwNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEzMWEzMTJhNDc4MDM1NGFiOWJmYzhlYTAyNjg0N2JhMTRmMTM1YWI4NzU0ZTJiZTM2NzYzNDNkNTA2NTE3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GPaUKfJ6Zonj0qy2cG5t25HLYojqwNekvvcsLmaPXCE)

I hope Embarcadero didn't break their fixes in 12.2
![image](https://github.com/user-attachments/assets/338e5f37-b3e8-4fd1-91bb-f792223547f7)

**Comment by OnePeople-source** [comment]
> > > I just add you to the list, can you try the demo here now : https://play.google.com/apps/internaltest/4701218363717235793 Say me what you think about it
> > 
> > 
> > Hi. I tried the demo and I have a question, in the demo scrollbox delphi controls, delphi controls use what rendering? After all, skia should draw the same as alcinoe in quality, and the smoothness should not be so deoghan!? And also the rendering performance is of course good, but what to do with creating a list of 10,000 controls, your library really lacks a fast listvew or better containerview (tlistbox delphi) only with fast component creation and smooth scrolling. Thanks in advance.
> 
> If you want to create a TListBox with 10,000 controls, it will never (never) be fast. You simply can't do that. You need to understand that every time you move the scrollbox of the TListBox by one pixel, you're also moving the position of all 10,000 controls.
> 
> To achieve this, you should create each control on the fly (and destroy them on the fly as well) so that the listbox only contains a few controls at any given time.
> 
> That's what we do in this app: https://www.youtube.com/watch?v=IJzEuZTSXDI&vq=hd2160
> 
> As for Skia, it's faster than CanvasGPU, but it's not magic either. :)

Yes, yes, I know that. I mean the component where you make a list item presentation like in Delphi listbox, and then the alcinoe component creates visible elements and removes invisible ones. That's why I have a question, if alcinoe controls are created slowly, how to do such scrolling? After all, even launching a frame from the alcinoe scrolling demo takes a very long time to start. Maybe you can add a demo, because according to your video it works very quickly. Sorry if I don't understand something.

**Comment by OnePeople-source** [comment]
@Zeus64 like fgx-native component "CollectionView"

**Comment by Zeus64** [comment]
Athens 12.2 with skia is now available on the master branch. Please give it a try.

I also have an online demo available at [this link](https://play.google.com/apps/internaltest/4701314002613599109), and I need 20 internal testers to make it public. If you're able to help, please send me your email so I can add you to the tester list.

Thanks for your support!

**Comment by maurobotta** [comment]
> I also have an online demo available at [this link](https://play.google.com/apps/internaltest/4701314002613599109), and I need 20 internal testers to make it public. If you're able to help, please send me your email so I can add you to the tester list.


Yes, I',m ready

**Comment by Zeus64** [comment]
can you gave me your android gmail email to stephane@magicfoundation.io so i can add it to the list ?

**Comment by Zeus64** [comment]
the link to download the app : 

![image](https://github.com/user-attachments/assets/fb0a68af-28de-42b3-8fbe-ef75f757ca14)

**Comment by maurobotta** [comment]
Hi,

I have any problems for use your great framework ( TAlEdit / TAlMemo.. ).
Do you have more specific step for use standard app ?
How / When use Merge.bat ?  Delphi project option modify ? How can i
convert a empty FMX Delphi project to Alcinoe+Skia ?

I can't found detailed info in your github page.

Mauro

Delphi 12.2






Il giorno mar 8 ott 2024 alle ore 14:38 Zeus64 ***@***.***>
ha scritto:

**Comment by maurobotta** [comment]
Hi @Zeus64 i have make a post here https://github.com/DelphiWorlds/Kastri/issues/277   i don't know is a Alcinoe or Kastri problem.

Thank you.
