### ISSUE TITLE
RAD 12.2 

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#332]
RAD 12.2 :
https://altd.embarcadero.com/download/radstudio/12.0/RADStudio_12_2_9782_9961F.iso

**Comment by firemen01** [comment]
Are you planning to remake the patch for 12.2?

**Comment by Zeus64** [comment]
Hello, yes i m very (very) close to commit the V2 of alcinoe with skia in mind

**Comment by Zeus64** [comment]
@firemen01 can you say me exactly what compoment of alcinoe you actualy use ?

**Comment by firemen01** [comment]
I only use the video player.

Can you tell me where the compression level of the APK is set?
On 12.1 my application is under 20 m., on 12.2 it is over 50. I checked the insides - all files are almost the same size. Or does the appt itself decide what compression level to use?

**Comment by firemen01** [comment]
empty application if developer then about 11 meters, if appstore I sign then 26! meters
how to deal with this?

**Comment by Zeus64** [comment]
it's maybe because you include the 32 bit binary inside for the app store, so you have the 32bit + 64bit binary (to binaries) when you upload to the app store

**Comment by firemen01** [comment]
unfortunately no, I only have lib\armeabi-v7a folder
try to build an empty project in developer and appstore modes. enabling Compress Dex files, Compress native library files in Application\Packaging helps

**Comment by OnePeople-source** [comment]
Skia library in lib, no?

**Comment by Zeus64** [comment]
Athens 12.2 is now available on the master branch. Please give it a try.

I also have an online demo available at [this link](https://play.google.com/apps/internaltest/4701314002613599109), and I need 20 internal testers to make it public. If you're able to help, please send me your email so I can add you to the tester list.

Thanks for your support!

**Comment by Zeus64** [comment]
> no. I don't use skia.
> 
> by the way, are you planning to switch to media3? https://developer.android.com/media/media3/exoplayer/migration-guide
> 
> in kastri they implemented this, but I didn't find support there z-order, it is very necessary

HI @firemen01

Done in the very last version available in the GIT we migrate to android MEDIA3 exoplayer
