### ISSUE TITLE
TALVideoPlayer component on iOS Metal renderer

### ISSUE THREAD

**Issue by VAlexeo** [MagicFoundation/Alcinoe#333]
I've modified TALVideoPlayer to be able to work on iOS Metal environment. The code is working itself or can be used as starting point for changes in a next release of Alcinoe.

Set GlobalUseMetal to True in your dpr to use Metal renderer.

[Alcinoe.FMX.VideoPlayer.txt](https://github.com/user-attachments/files/17131858/Alcinoe.FMX.VideoPlayer.txt)

**Comment by Zeus64** [comment]
thanks [VAlexeo](https://github.com/VAlexeo), i already put it in the skia branch that will be very soon the master branch.
Next time do not hesitate to propose a change directly https://github.com/MagicFoundation/Alcinoe?tab=readme-ov-file#propose-a-change-using-github it's will be more easy for me to approuve and merge :)  

thanks again !
