### ISSUE TITLE
Declared a function in interface section of the unit ALXmlDoc, so that it can be accessed in other units.

### ISSUE THREAD

**Issue by shanthipriyapakkela** [MagicFoundation/Alcinoe#336]
"**Undeclared identifier**" was returned when we attempted to use a function in the **unit ALXmlDoc**.
 I have declared the function "**ALCreateXmlNode**" in the interface section to prevent this exception. 
I'm not sure if it affects other functionalities.

The function is :
**function ALCreateXmlNode(const NameOrData: AnsiString;
                         NodeType: TALXMLNodeType = ntElement;
                         const AddlData: AnsiString = ''): TALXMLNode;**

**Comment by Zeus64** [comment]
hello, yes ALCreateXmlNode is an internal function, you must use instead TALXMLDocument.CreateNode
