### ISSUE TITLE
Delphi12.2 can't compile ALFMXControls demo 

### ISSUE THREAD

**Issue by davidham2020** [MagicFoundation/Alcinoe#338]
Dear Mr Zeus64 Please help.
I was compiling the ALFMXControls demo on delphi 12.2 but  it show error
[DCC Warning] Alcinoe.FMX.Layouts.pas(8): W1054 Check if FMX.Layouts.pas was not updated and adjust the IFDEF
[DCC Error] Alcinoe.FMX.Layouts.pas(60): E2137 Method 'IsVisibleObject' not found in base class
[DCC Error] Alcinoe.FMX.Layouts.pas(154): E2137 Method 'ChildrenMouseDown' not found in base class
[DCC Error] Alcinoe.FMX.Layouts.pas(155): E2137 Method 'ChildrenMouseMove' not found in base class
[DCC Error] Alcinoe.FMX.Layouts.pas(156): E2137 Method 'ChildrenMouseUp' not found in base class
[DCC Error] Alcinoe.FMX.Layouts.pas(157): E2137 Method 'ChildrenMouseLeave' not found in base class
[DCC Fatal Error] UnitMain.pas(21): F2063 Could not compile used unit 'Alcinoe.FMX.Layouts.pas'
Failed
Elapsed time: 00:00:00.6
As shown in the capture
![图片](https://github.com/user-attachments/assets/84edeb3e-1bc1-4042-9753-f00d484cbb0c)
![图片](https://github.com/user-attachments/assets/40fa5e82-73ba-43c7-b06a-9c8c9b5c0a1b)
And I already add in delphi 12.2  Tools-> Options -> Language-> Delphi-> Library -> Library path (Platform Android 32-bit) follwing like this
$(BDSLIB)\Alcinoe\Source;
$(BDSLIB)\Alcinoe\Embarcadero\Athens\fmx;
$(BDSLIB)\Alcinoe\Embarcadero\Athens\rtl;
$(BDSLIB)\Alcinoe\Embarcadero\Athens\rtl\ios;
$(BDSLIB)\Alcinoe\Embarcadero\Athens\rtl\osx;
$(BDSLIB)\Alcinoe\Embarcadero\Athens\rtl\android

**Comment by Zeus64** [comment]
please wait end of the day, i will commit a new version of Alcinoe with Athens 12.2 support

**Comment by davidham2020** [comment]
thank you very much.

**Comment by Zeus64** [comment]
Athens 12.2 is now available on the master branch. Please give it a try.

I also have an online demo available at [this link](https://play.google.com/apps/internaltest/4701314002613599109), and I need 20 internal testers to make it public. If you're able to help, please send me your email so I can add you to the tester list.

Thanks for your support!

**Comment by davidham2020** [comment]
Thank you very much! I'm late and didn't get your internal testing qualification. Here is my email address
davidham2010@gmail.com
