### ISSUE TITLE
Demo app 90 - 120 Hz

### ISSUE THREAD

**Issue by OnePeople-source** [MagicFoundation/Alcinoe#340]
Hello, the demo application has a limit of 60hz, so everything does not look smooth on my One Plus 7 pro (90hz), is there any way to add synchronization to the maximum supported screen frequency?

**Comment by Zeus64** [comment]
Hello no the demo work with 90hz, if you click the TALScrollBox demo you can see on the top the fps that is 90 fps. if you see only 60 fps then maybe your phone is only 60hz? on my google pixel 7 that is 90 hz i see 90 fps

**Comment by Zeus64** [comment]
I'll close the issue for now. If you have any more information, feel free to reopen it.
