### ISSUE TITLE
Alcinoe.FMX.Types3D; [DCC Error] Alcinoe.FMX.Types3D.pas(277): Undeclared identifier: 'Material'

### ISSUE THREAD

**Issue by firemen01** [MagicFoundation/Alcinoe#341]
[DCC Error] Alcinoe.FMX.Types3D.pas(277): Undeclared identifier: 'Material'
[DCC Error] Alcinoe.FMX.Types3D.pas(295): Undeclared identifier: 'Material'
[DCC Error] Alcinoe.FMX.Types3D.pas(311): Undeclared identifier: 'Material'
[DCC Error] Alcinoe.FMX.Types3D.pas(312): Undeclared identifier: 'External'

[DCC Error] Alcinoe.FMX.Types3D.pas(312): Incompatible types: 'Integer' and 'TTextureStyle'

**Comment by firemen01** [comment]
I don't have iOS or Mac installed. I think like many others.
It is advisable to separate Athens.patch for different configurations and check the folders. Otherwise, due to the fact that there are no files, it crashes, and all screen messages are disabled for you.

**Comment by Zeus64** [comment]
hmm  Alcinoe.FMX.Types3D.pas is not related to mac or ios.
are you sure you patched the delphi source core ?
you must run {alcinoe}\CompileAll.bat and select yes to "Copy the Delphi source code and patch it locally (Y/N, default=Y)"

**Comment by firemen01** [comment]
the patch didn't work until I removed all the links to the Mac iOS files from the patch that I don't have.
but otherwise everything works, thanks!

**Comment by Zeus64** [comment]
but their is no link to the Mac iOS files ? with link did you remove ?

**Comment by firemen01** [comment]
Index: Embarcadero/Athens/fmx/FMX.Canvas.Mac.pas
Index: Embarcadero/Athens/fmx/FMX.Context.GLES.iOS.pas
Index: Embarcadero/Athens/fmx/FMX.Context.Mac.pas
Index: Embarcadero/Athens/fmx/FMX.Platform.iOS.pas

**Comment by Zeus64** [comment]
Oh, i see so you use only on Android ? you don't develop for ios too?

**Comment by Zeus64** [comment]
yes now with athens 12.2 you only need one R.jar :)

**Comment by cleyjulio** [comment]
> [Erro DCC] Alcinoe.FMX.Types3D.pas(277): Identificador não declarado: 'Material' [Erro DCC] Alcinoe.FMX.Types3D.pas(295): Identificador não declarado: 'Material' [Erro DCC] Alcinoe.FMX.Types3D.pas(311): Identificador não declarado: 'Material' [Erro DCC] Alcinoe.FMX.Types3D.pas(312): Identificador não declarado: 'Externo'
> 
> [Erro DCC] Alcinoe.FMX.Types3D.pas (312): Tipos incompatíveis: 'Integer' e 'TTextureStyle'

I have this same error. However, I develop for Mac, iOS and Android. How do I fix it?

**Comment by Zeus64** [comment]
@cleyjulio did you run Alcinoe\Embarcadero\Athens\Update.bat ? what the result, can you add here a print screen ?
did you also included in the search path of your project :

Alcinoe\Embarcadero\Athens\fmx\
Alcinoe\Embarcadero\Athens\rtl\common\

**Comment by cleyjulio** [comment]
I Run the update.bat with success.... add in the search path  Alcinoe\Embarcadero\Athens\fmx
Alcinoe\Embarcadero\Athens\rtl\common\

**Comment by Zeus64** [comment]
Can you update the Alcinoe repository and run again Alcinoe\Embarcadero\Athens\Update.bat ? now you must have Alcinoe\Embarcadero\Athens\data\firedac and then you can add this directory to the search path.

Note: I m actively working with embarcadero to correct all the bug in the original source file. I hope in the next release of delphi we will not need anymore to patch the original source file

**Comment by cleyjulio** [comment]
Now return this error: [DCC Fatal Error] FireDAC.Phys.SQLPreprocessor.pas(11): F1026 File not found: 'FireDAC.inc'

**Comment by Zeus64** [comment]
can you check if you have FireDAC.inc is in Alcinoe\Embarcadero\Athens\data\firedac\ (normaly yes)

**Comment by cleyjulio** [comment]
I couldn't find FireDAC.inc, not even in the Delphi folder. Both (Alcinoe and Embarcadero) only have the following files:

FireDAC.Phys.pas
FireDAC.Phys.SQLGenerator.pas
FireDAC.Phys.SQLGenerator.pas

**Comment by Zeus64** [comment]
Hmm, so it's look like you do not have the source of fireDAC, with version of delphi do you have ?

**Comment by cleyjulio** [comment]
I don't have the source code. My version is the simplest: Professional.
12.2 Patch 2

Could you send me the file please? cleyjulio@gmail.com

**Comment by cleyjulio** [comment]
this file too not found: FireDAC.Stan.Config.inc

**Comment by Zeus64** [comment]
I can't send you the pas as its copyright, but maybe i can sent you the precompiled DCU for alcinoe. I will look for it tomorow

**Comment by cleyjulio** [comment]
I get files: FireDAC.inc and FireDAC.Stan.Config.inc, but this error ocour again: F2051 Unit FireDAC.FMXUI.Wait was compiled with a different version of FMX.Forms.Application

**Comment by Zeus64** [comment]
yes, you also need  FireDAC.FMXUI.Wait.pas, you need all Firedac.*.pas

**Comment by cleyjulio** [comment]
I get all FireDACs files... but now, when open form with TALMemo happens this error: Project raised exception class EJNIFatal with message 'Java type io/magicfoundation/alcinoe/edittext/ALKeyPreImeListener could not be found'.

**Comment by Zeus64** [comment]
yes, you must add in your project file the java file : Alcinoe\Libraries\jar\io\magicfoundation\alcinoe\alcinoe-edittext\1.0.0\alcinoe-edittext-1.0.0.jar

**Comment by cleyjulio** [comment]
thanks! Works fine!

**Comment by Zeus64** [comment]
perfect happy that it's finally work! I close this jira for now
