### ISSUE TITLE
Bitmap in TALRectangle

### ISSUE THREAD

**Issue by gonzzzales** [MagicFoundation/Alcinoe#342]
Hi @Zeus64. 
Thanks a lot for your work!
How can i use bitmap for TALRectangle in runtime?
In previos version it was
Fill.Kind := TBrushKind.Bitmap;
Fill.Bitmap.WrapMode := TWrapMode.TileStretch;
Fill.Bitmap.Bitmap.Assign(Bitmap1);

Now i see in demo, that i need to use resources, but i dont undestand, how.

**Comment by Zeus64** [comment]
hello, yes bitmap in the *.fmx cause some performance probleme. so now all image must be in resource. for this it's simple: 

* on the directory of your project create a /Resources/ subdirectory
* inside store the png or jpg of your image
* in delphi, do project > Resource and Images > and add  your image (same name as the file name without the extension)
* then in the fill property of the TALRectangle simply gave the name of the resource you just added

**Comment by gonzzzales** [comment]
Is it possible to do it in runtime? in my application i have some images, that i have previosly downloaded from server. And now i need to use one of them, but it is dynamicly, i have only a path to the image.

**Comment by Zeus64** [comment]
yes, so in such way in the resourcename, simply put the full path of your image

**Comment by gonzzzales** [comment]
Thanks, i will try!!!
