### ISSUE TITLE
CompileAll.bat don't work with custom path

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#343]
Hi

I have download last version of Alcinoe, when run CompileAll.bat , it don't work, 

i have installed Delphi on V:\Delphi12,  I'm having trouble with these files, but to no avail.

CompileAll.bat
CompileJar.bat
InitEnvironment.bat

IniEnviromento.bat i have force set ALDelphiDir=V:\DelphiXE12\

but show this error: ( see space in "V:\DelphiXE12\ source\fmx" )

------------------
Delphi source code
------------------

Copy the Delphi source code and patch it locally (Y/N, default=Y)?: y

Copy "V:\DelphiXE12\ source\fmx"
Impossibile trovare il file - fmx
0 File copiati

**Comment by firemen01** [comment]
ALDelphiDir=V:\DelphiXE12
without a slash at the end
maybe it will help

**Comment by Zeus64** [comment]
Just fixed in the last commit, you can update your repository

**Comment by maurobotta** [comment]
Hi, i have a create a empty new directory for Alcinoe Commits on Oct 16, 2024. Downloaded now. 

Dont' work.

I have a custom path for Delphi 12.2 ( V:\DelphiXE12 ) :  Error a SPACE char here : "V:\DelphiXE12\ source\fmx"
Run:   CompileAll.bat

--------
Compiler
--------

1) Athens
2) Alexandria (deprecated)
Enter number to select a compiler (Empty to auto select): 1

------------------
Delphi source code
------------------

Copy the Delphi source code and patch it locally (Y/N, default=Y)?:
Copy "V:\DelphiXE12\ source\fmx"
Impossibile trovare il file - fmx

0 File copiati

**Comment by Zeus64** [comment]
I not sure I understand what wrong in your setup, can you look in your registry at 

HKLM\SOFTWARE\WOW6432Node\Embarcadero\BDS\23.0
in the key RootDir
if their is a space ?

**Comment by Zeus64** [comment]
Ok I Think I found. I just commit a fix, can you try to update your master branch and try again ?

**Comment by maurobotta** [comment]
YES

**Comment by maurobotta** [comment]
NEW OUTPUT:



--------
Compiler
--------

1) Athens
2) Alexandria (deprecated)
Enter number to select a compiler (Empty to auto select): 1

------------------
Delphi source code
------------------

Copy the Delphi source code and patch it locally (Y/N, default=Y)?:

Copy "V:\DelphiXE12\source\fmx"
314 File copiati
Copy "V:\DelphiXE12\source\rtl\common\System.Skia.API.pas"
        1 file copiati.
Patch the locally copied source code
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.D2D.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.GDIP.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.GPU.Helpers.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.GPU.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.Mac.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.DX11.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.DX9.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.GLES.Android.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.GLES.iOS.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.GLES.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.Mac.pas...
Checking patch Embarcadero/Athens/fmx/FMX.....




Working....

**Comment by Zeus64** [comment]
perfect :)
