### ISSUE TITLE
TALSwitch.Transition

### ISSUE THREAD

**Issue by gonzzzales** [MagicFoundation/Alcinoe#344]
Hi @Zeus64 

Please tell me, how to use TALSwitch.Transition if i create TALSwitch dynamicly.
I tryed to do this in constructor
 Transition := TALStateTransition.Create(1);
  Transition.BeginUpdate;
  Transition.AnimationType := TAnimationType.InOut;
  Transition.Interpolation := TALInterpolationType.Cubic;
  Transition.Duration := 1;
  Transition.EndUpdate;

But i dont see animation.
In your demo-project with static Switch it work fine

**Comment by Zeus64** [comment]
You do not need to create any TALStateTransition.
just do : 

MySwitch := TALSwitch.create(OwnerControl);
MySwitch.parent :=  OwnerControl;
MySwitch.Transition.Duration := 0.2;

that all

aditionally you can also apply a style to the newly created TALSwitch, for exemple : 

ALApplySwitchTheme('Material3.Light', MySwitch);

**Comment by gonzzzales** [comment]
I have found it

if i make something like this
ALSwitch1.Checked = true

transition not work, it work only if i click directly to Switch.

May be is it possible to start transition programmatically?

**Comment by Zeus64** [comment]
Ah yes exactly, the transition work only if user interact with the Switch. if you want to programatiqually start the transition you must do :

ALSwitch1.Checked = true;
ALSwitch1.StartTransition;

**Comment by gonzzzales** [comment]
Thanks. Work fine!!!
