### ISSUE TITLE
May I ask why ALLiveVideoChat is not working 

### ISSUE THREAD

**Issue by davidham2020** [MagicFoundation/Alcinoe#345]
Dear Mr Zeus64 Please help.
I have successfully compiled both the server-side and client-side of ALLiveVideoChat on delphi 12.2, and have also started the server-side and set the IP address of the client and the server in the same network segment. However, when I opened the client-side on my phone and clicked on the connection, there was no response and it didn't seem to be working. May I ask what is the reason for this? Could you please help me solve it? 
Thank you very much!

**Comment by Zeus64** [comment]
Hi @davidham2020,

First, I am looking for someone who needs WebRTC and can update the current wrapper to the latest version provided by Google, if you are interested just contact me :) Regarding the issue you're experiencing, please note that the wrapper is quite old (2-3 years), and I believe the demo uses STUN/TURN servers from Xirsys. It's possible that those servers are no longer operational. :(

```
  setlength(LIceServers, 6);
  with LIceServers[0] do begin
    uri := 'stun:eu-turn1.xirsys.com';
    username := '';
    password := '';
  end;
  //-----
  with LIceServers[0] do begin
    uri := 'turn:eu-turn1.xirsys.com:80?transport=udp';
    username := '54c4553a-0427-11e9-bbd8-e8cee7e120e9';
    password := '54c455b2-0427-11e9-909e-55b82d8eaa45';
  end;
  //-----
  with LIceServers[1] do begin
    uri := 'turn:eu-turn1.xirsys.com:3478?transport=udp';
    username := '54c4553a-0427-11e9-bbd8-e8cee7e120e9';
    password := '54c455b2-0427-11e9-909e-55b82d8eaa45';
  end;
  //-----
  with LIceServers[2] do begin
    uri := 'turn:eu-turn1.xirsys.com:80?transport=tcp';
    username := '54c4553a-0427-11e9-bbd8-e8cee7e120e9';
    password := '54c455b2-0427-11e9-909e-55b82d8eaa45';
  end;
  //-----
  with LIceServers[3] do begin
    uri := 'turn:eu-turn1.xirsys.com:3478?transport=tcp';
    username := '54c4553a-0427-11e9-bbd8-e8cee7e120e9';
    password := '54c455b2-0427-11e9-909e-55b82d8eaa45';
  end;
  //-----
  with LIceServers[4] do begin
    uri := 'turns:eu-turn1.xirsys.com:443?transport=tcp';
    username := '54c4553a-0427-11e9-bbd8-e8cee7e120e9';
    password := '54c455b2-0427-11e9-909e-55b82d8eaa45';
  end;
  //-----
  with LIceServers[5] do begin
    uri := 'turns:eu-turn1.xirsys.com:5349?transport=tcp';
    username := '54c4553a-0427-11e9-bbd8-e8cee7e120e9';
    password := '54c455b2-0427-11e9-909e-55b82d8eaa45';
  end;
```

**Comment by davidham2020** [comment]
Dear Zeus64,
Thank you very much for your reply! As you said, I am quite interested in WebRTC. If you have a new version, I am willing to participate in testing. Thank you again!
