### ISSUE TITLE
[BUG] TAlEdit is not correct initialize VISIBLE on open form

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#350]
Hi,
i have a FMX application con any forms, i'm trying converting frm FMX To new Skia / Alicinoe ( TALEdit ),

i have found a bug with TAlEdit it is not correct initialize VISIBLE when form is opened.

My easy example:

Form FMX -> 1 Tab Control , 3 Tab Item inside,

on the TAB n.1 Empty
on the TAB n.2 insert a TALRectangle **WITH  VISIBLE FALSE** and inside a TALEDIT with Background color and TExt = 'AAAAA'
on the TAB n.3 insert a TALEDIT **WITH VISIBLE FALSE** and Background color and TExt = 'BBB'

At runtine, when open form ( TAB Page n.1 ) you can see the n. 2 edit ( Bug ) text AAAAA     BBBBBB.

Target OS Compile: "Windows 32" and "Android 64"
Device: Samsung S24 U Android 14
Delphi 12.2

Mauro

**Comment by Zeus64** [comment]
Corrected in the last release. please update the repository
