### ISSUE TITLE
scrollengine in TALTabContol

### ISSUE THREAD

**Issue by gonzzzales** [MagicFoundation/Alcinoe#351]
Hi @Zeus64 !!!
Please two words about properties in ScrollEngine of TALTabControl, how to increase swipe sensitivity, how to use
    ScrollEngine.DragResistanceFactor
    ScrollEngine.OverflingDistance
    ScrollEngine.TouchSlop
    ScrollEngine.TimerInterval

**Comment by maurobotta** [comment]
Yes, i'm testing, too, now.

I need extra info of ScrollEngine with ListView...

**Comment by Zeus64** [comment]
regarding : 

**ScrollEngine.DragResistanceFactor**

    A multiplier applied during drag operations to simulate resistance. A value
    of 1 implies normal drag behavior, while values below 1 introduce increased
    resistance, making the drag feel heavier.

**ScrollEngine.OverflingDistance**
  
    It's the Max distance to overfling for edge effects. you don't need it with TALTabControl

**ScrollEngine.TouchSlop**

  Distance a touch can wander before we think the user is scrolling. Better to not touch it if the TalTabControl is inside a scrollbox

**ScrollEngine.TimerInterval**

    Specifies the duration between offset recalculations. We don't use
    TimerInterval for Android/iOS since we utilize DisplayLink and JChoreographer

**Comment by gonzzzales** [comment]
@Zeus64 Thanks a lot!!!
