### ISSUE TITLE
Error compiling  Method 'IsVisibleObject' not found in base class ( Alcinoe.FMX.Layouts.pas )

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#352]
Hi

I have a my project FMX with ALEdit all work fine,  but i have make a test with ScrollEngine and i need Alcinoe.FMX.Layouts.pas ( Delphi Ide add this unit )

Now i can't compile my project.

[DCC Error] Alcinoe.FMX.Layouts.pas(122): E2137 Method 'IsVisibleObject' not found in base class
If i remark 10 lines in Alcinoe.FMX.Layouts.pas  all compile fine.

Hint ?

p.s.
TALTabControl -> Alcinoe.FMX.TabControl

Target OS Compile: "Windows 32" and "Android 64"
Device: Samsung S24 U Android 14
Delphi 12.2

Mauro

![image](https://github.com/user-attachments/assets/cf42c5cd-0cde-4f08-bad3-b93a63d5ea2e)

**Comment by Zeus64** [comment]
It's because you must include in the search path of you project Alcinoe\Embarcadero\Athens\fmx and Alcinoe\Embarcadero\Athens\rtl\common\

**Comment by maurobotta** [comment]
Hi, my project ( TALEdit / TALMemo / TALRectangle ) compiled fine ( the path was correct ).  

yes have already these path Alcinoe\Embarcadero\Athens\fmx  and Alcinoe\Embarcadero\Athens\rtl\common\

but when i add a TALTabControl  or a EngineScroll class don't compile more. (  i have remark 10 lines for work ).


![image](https://github.com/user-attachments/assets/b9da5dd5-0149-4231-9ce2-f5336cb262c5)

**Comment by Zeus64** [comment]
can you make me a sample project so i can investigate what not working ?
