### ISSUE TITLE
TALTabControl - TAB is not visible

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#354]
Hi

I'm testing a TALTabControl -> TALTabItem,  i can't know how view "TAB" ( Android / IOS / Win ).

Last version of Alcinoe.

Delphi 12.2

Mauro

**Comment by Zeus64** [comment]
What you mean by view "TAB" ?  you mean this : 

![image](https://github.com/user-attachments/assets/ba7fd75f-85bc-4504-954a-9018fb4ec7fc)

**Comment by maurobotta** [comment]
YES

**Comment by Zeus64** [comment]
Ah, no, TALTabControl doesn't include that feature. There are so many different possible styles for tabs—such as displaying them on the left, at the top, as images, text, etc. (see: https://m3.material.io/components/tabs/guidelines)—that I've chosen not to include the tabs in TALTabControl. Instead, developers can add their own buttons or elements to represent the tabs as they see fit.
 
TALTabControl is mainly to do stuff like this : 

![image](https://github.com/user-attachments/assets/316910c6-f1d3-4bbe-9a6c-da998f842cb3)

![image](https://github.com/user-attachments/assets/adaa3c66-369d-4f4f-8a96-559b4ebc2100)

**Comment by maurobotta** [comment]
@Zeus64  Thank you, another question , How i can Active Material 3 Controls ( Dersign )  ?

FMX TStyleBook  remove it ?

![image](https://github.com/user-attachments/assets/5431e91a-17dd-4331-9f23-d80834b03652)

**Comment by maurobotta** [comment]
@Zeus64, How can to have TALEdit with MAT3 design  ?



Thank you for yor work :)

**Comment by Zeus64** [comment]
You don't need FMX TStyleBook, none of the alcinoe control work with it. in delphi, you right click on a TEdit, and you choose the material 3 design style you want in the popup list

![theme](https://github.com/user-attachments/assets/2abe23a2-08d4-4a86-9bcf-824e223c9674)

**Comment by Elinulok32** [comment]
How then do you activate Material 3 Controls (at Runtime). I have a series of checkboxes that are created at runtime and I need them to have the Material 3 Theme. Thank you.

**Comment by Zeus64** [comment]
Hello, At runtime you need to play with Alcinoe.FMX.Themes.pas
inside you have the function ALApplyCheckBoxTheme

just execute it on your checkbox like : 

ALApplyCheckBoxTheme('Material3.Light', MyCheckBox);

you can also write your custom theme if you want
