### ISSUE TITLE
TALVertScrollBox support onCalcContentBounds ?               UpdateKBBounds..

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#357]
Hi @Zeus64 

I need show  a Virtual Keyboard on TALEdit.

I'm using Delphi sample:
https://github.com/Embarcadero/RADStudio12Demos/blob/main/Object%20Pascal/Multi-Device%20Samples/User%20Interface/KeyboardTypes/VirtualKeyboardBase.pas

But i have a problem with :

( TALVertScrollBox )
MyALVertScrollBox.OnCalcContentBounds := CalcContentBoundsProc;

OnCalcContentBounds Not exist.  

How i can to use the virtual keyboard on TALVertScrollBox -> TALEdit  with Edit in bottom position ?

Last Alcinoe source.
Android / ios.

Mauro

**Comment by Zeus64** [comment]
Yes, their is no OnCalcContentBounds  in TALALVertScrollBox. Instead for the virtual keyboard you must simply add padding at the bottom of the form. take a look at the ALFmxControls Demo

**Comment by maurobotta** [comment]
yes, work fine
