### ISSUE TITLE
Missing HINT property in TALText , TALEdit...

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#358]
Hi @Zeus64 

I'm converting my big App FMX from FMX To Alcinoe.

I have see the property HINT is not available in your components, now.

The main problem is not the white box is missing but i have more lines of code ( and Fmx forms ) where HINT property is used like a Tag property , with ShowHint set to False, for save information at runtime.

os:
Android / ios / Window.

Hint ?

Best Regards

Mauro Botta

![image](https://github.com/user-attachments/assets/a0007606-c172-4a1b-b68f-7e569be932e9)

**Comment by Zeus64** [comment]
Yes Hint is a bad approach for mobile app as it's impracticable on touch screen, this why it's was hidden in Alcinoe. 
Do you need the hint as text container during runtime or at design time ?

**Comment by maurobotta** [comment]
>> Do you need the hint as text container during runtime or at design time ?
yes

If i remove the Remark for TALText in .pas source, work fine ?

**Comment by Zeus64** [comment]
Yes it's should work fine, especially that you use it only as a text container.
