### ISSUE TITLE
TALEdit - How Selection Text ( SelStart property ) ?

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#359]
Hi @Zeus64 ,  it is last question for this week  :)

I have TALEdit. how i can select a parzial text ( SelStart property ) , select first 3 char  of long text ?

ediText.SelStart := 4;
ediText.SelStart := Length(ediText.Text);

Thank you again

Mauro

https://github.com/MagicFoundation/Alcinoe/blob/master/Archive/Source/ALEdit.pas

**Comment by Zeus64** [comment]
Right now we can not, we must add this functionality. it's would be not very difficult to do it by the way

**Comment by Zeus64** [comment]
It's just implemented in the last commit. Just update your repository. you can now use

`MyEdit.SetSelection()`
