### ISSUE TITLE
[BUG] TALEdit onEnter / onExit never called

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#361]
Hi @Zeus64 

I have found a bug of TALEdit onEnter / onExit properties are never called.

See image in attach.

Mauro

Test Win32, only.

p.s.
 I see TAlEdit don't have .OnTyping this is very important problem. 
 i can't use Timer 300 ms when i stop write in TALEdit ( List Customers  + Edit Search  ). No key-return required.

![image](https://github.com/user-attachments/assets/6f597575-e9d7-4646-8375-4cbcfeea1c81)

**Comment by Zeus64** [comment]
Corrected in the latest commit, plus update your repository.

Regarding OnTyping, you must use instead OnChange, that behave the same.

**Comment by maurobotta** [comment]
OnChange  is called with this code:         Edit1.text := 'xxxxx'  ?

**Comment by Zeus64** [comment]
> OnChange is called with this code: Edit1.text := 'xxxxx' ?

yes, their was a little bug in the windows version, i just commited the fix, please update your repository
