### ISSUE TITLE
Why does the TilerEffect under TALVideoPlayer in ALFmxControl demo display a color bar?

### ISSUE THREAD

**Issue by davidham2020** [MagicFoundation/Alcinoe#362]
Dear Zeus64,
May I ask why the TilerEffect in the TALVideoPlayer demo of ALFmxControl displays a color bar? Please help solve it! Thank you very much!
![ColorBar](https://github.com/user-attachments/assets/7e1d2965-c46a-4679-8c38-7553a8565751)

**Comment by Zeus64** [comment]
Hello, sound very strange, I never have this. could you try on another phone ? what phone are you using ?

**Comment by davidham2020** [comment]
I'm very sorry for wasting your time!
It was my negligence in not carefully reading your instructions. I enabled Skia, which caused this problem. Thank you very much!
