### ISSUE TITLE
Android merger error

### ISSUE THREAD

**Issue by OnePeople-source** [MagicFoundation/Alcinoe#363]
Delphi 12.2 Error  SDKAaptPath is not configured
SDKAaptPath is not in HKEY_CURRENT_USER\Software\Embarcadero\BDS\23.0\PlatformSDKs\AndroidSDK25.2.5_32bit.sdk

**Comment by Zeus64** [comment]
You use an old version of alcinoe. you need to use the last one. SDKAaptPath have been removed in Delphi 12.2

**Comment by OnePeople-source** [comment]
> You use an old version of alcinoe. you need to use the last one. SDKAaptPath have been removed in Delphi 12.2

But in new version TALRectangle.Fill.Bitmap is over(

**Comment by Zeus64** [comment]
no really, you can use instead TALRectangle.Fill.ResourceName ... can you show me the code where you need a TBitmap ?

**Comment by OnePeople-source** [comment]
I load my skin from my xml file and 
    if rLoad.Fill.Kind = TBrushKind.Bitmap then
                        begin
 rLoad.Fill.Bitmap.Bitmap.LoadFromFile(bmRectPath);

 if (rLoad.Fill.Kind = TBrushKind.Solid) and
                          (rLoad.TagString <> 'Fill') then
                        begin
                            TAnimator.AnimateColor(rLoad, 'Fill.Color',
                              StringToAlphaColor(JSONPar.GetChildNodeValueText
                              ('fill', '0')), AnimationTime);

...............

**Comment by Zeus64** [comment]
Try to do something like : 

rLoad.Fill.resourceName := bmRectPath

**Comment by OnePeople-source** [comment]
> Try to do something like :
> 
> rLoad.Fill.resourceName := bmRectPath

But if i need Bitmap.assign(rLoad.Fill.Bitmap)?

**Comment by OnePeople-source** [comment]
And in general, the old bitmap system was better. I have 100,000 lines of code in my application with a bitmap download, I don't want to redo everything at all (

**Comment by Zeus64** [comment]
I understand. Unfortunately the bitmap was removed from the fill property for performance reason. Their is no plan to add it back :(

**Comment by Zeus64** [comment]
I close this jira for now, I just advise you to use TRectangle where you need TBitmap and for other you can use TALRectangle
