### ISSUE TITLE
[REQ] How optimize TListView scroll ?

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#365]
Hi @Zeus64 

We are near to closing the conversion of my App from Fmx To Alcinoe / SKIA.
The new App is more fluid, modern,  fast,  i have remove TListBox and add any TAlText, now the scroll is VERY FAST.

One of the things I can't take away, it would be too much work are **TListView** ( Customers List ).

Do you have any hint for optimize scroll of TALVertScrollBox ->TListView ?

( Styled ? DynamicAppearance, TTextObjectAppearance.. , TListViewItemText... )

**Make  a patch of TListView.pas to use it inside TAlText ?**

"C:\Users\Public\Documents\Embarcadero\Studio\23.0\Samples\Object Pascal\Multi-Device Samples\User Interface\ListView\ListViewMultiDetailAppearance\"

![image](https://github.com/user-attachments/assets/81a9ffcc-fd78-40bd-8805-b8e9f4584788)

**Comment by Zeus64** [comment]
Hi, regarding TListBox, I’m currently working on a TALDynamicScrollBox. In short, it functions similarly to TListBox but is extremely fast and capable of handling millions of items, as items are dynamically loaded and destroyed on the fly. I hope it will be ready by Q1 2025. Unfortunately, at the moment, we don’t have any alternative solution to replace TListBox.
