### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by ThePrefontaine** [MagicFoundation/Alcinoe#369]
Using Delphi 12.1 on Windows 11.

Following the instructions under "Install Alcinoe" I ran CompileAll.bat and got the following output: (its long, sorry)

--------------------
Copy "C:\Program Files (x86)\Embarcadero\Studio\23.0\source\fmx"
273 File(s) copied
Copy "C:\Program Files (x86)\Embarcadero\Studio\23.0\source\rtl\common\System.Skia.API.pas"
        1 file(s) copied.
Copy "C:\Program Files (x86)\Embarcadero\Studio\23.0\source\data\firedac"
3 File(s) copied
Patch the locally copied source code
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.D2D.pas...
error: while searching for:
    procedure DoExcludeClipRect(const ARect: TRectF); override;?
  public?
    destructor Destroy; override;?
    procedure SetSize(const AWidth, AHeight: Integer); override;?
    { caps }?
    class function GetAttribute(const Value: TCanvasAttribute): Integer; override;?
    { brushes }?

error: patch failed: Embarcadero/Athens/fmx/FMX.Canvas.D2D.pas:233
error: Embarcadero/Athens/fmx/FMX.Canvas.D2D.pas: patch does not apply
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.GDIP.pas...
error: while searching for:
    procedure DoExcludeClipRect(const ARect: TRectF); override;?
  public?
    destructor Destroy; override;?
    procedure SetSize(const AWidth, AHeight: Integer); override;?
    { brushes }?
    class function CalculateStrokeBrush(const ABrush: TStrokeBrush): TStrokeBrush; overload; inline;?
    class function CalculateBrush(const ABrush: TBrush): TBrush; overload; inline;?

error: patch failed: Embarcadero/Athens/fmx/FMX.Canvas.GDIP.pas:101
error: Embarcadero/Athens/fmx/FMX.Canvas.GDIP.pas: patch does not apply
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.GPU.Helpers.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.GPU.pas...
error: while searching for:
    class function CalculateStrokeBrush(const ABrush: TStrokeBrush): TStrokeBrush; overload; inline;?
    class function CalculateBrush(const ABrush: TBrush): TBrush; overload; inline;?
    { buffer }?
    procedure SetSize(const AWidth, AHeight: Integer); override;?
    { drawing }?
    procedure MeasureLines(const ALines: TLineMetricInfo; const ARect: TRectF; const AText: string; const WordWrap: Boolean;?
      const Flags: TFillTextFlags; const ATextAlign: TTextAlign; const AVTextAlign: TTextAlign = TTextAlign.Center); override;?

error: patch failed: Embarcadero/Athens/fmx/FMX.Canvas.GPU.pas:167
error: Embarcadero/Athens/fmx/FMX.Canvas.GPU.pas: patch does not apply
Checking patch Embarcadero/Athens/fmx/FMX.Canvas.Mac.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.DX11.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.DX9.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.GLES.Android.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.GLES.iOS.pas...
error: Embarcadero/Athens/fmx/FMX.Context.GLES.iOS.pas: No such file or directory
Checking patch Embarcadero/Athens/fmx/FMX.Context.GLES.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.Mac.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Context.Metal.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Controls.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Controls3D.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Filter.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Forms.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Forms3D.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Graphics.pas...
Hunk #9 succeeded at 7683 (offset -1 lines).
Checking patch Embarcadero/Athens/fmx/FMX.Platform.iOS.pas...
error: Embarcadero/Athens/fmx/FMX.Platform.iOS.pas: No such file or directory
Checking patch Embarcadero/Athens/fmx/FMX.Platform.Screen.Android.pas...
error: while searching for:
?
function TAndroidScreenServices.TryFillDisplayInfo(const ANativeDisplay: JDisplay; var ADisplay: TDisplay): Boolean;?
?
   function ScaleRect(const ARect: TRect; const AScale: Single): TRect;?
   begin?
     Result.Left := Trunc(ARect.Left / AScale);?
     Result.Right := Ceil(ARect.Right / AScale);?
     Result.Top := Trunc(ARect.Top / AScale);?
     Result.Bottom := Ceil(ARect.Bottom / AScale);?
   end;?
?
  function CalculatePhysicalWorkarea(const ANativeDisplay: JDisplay; const APhysicalBounds: TRect): TRect;?

error: patch failed: Embarcadero/Athens/fmx/FMX.Platform.Screen.Android.pas:255
error: Embarcadero/Athens/fmx/FMX.Platform.Screen.Android.pas: patch does not apply
Checking patch Embarcadero/Athens/fmx/FMX.Platform.UI.Android.pas...
error: while searching for:
end;?
?
procedure TAndroidWindowHandle.TFormViewListener.onSizeChanged(w, h, oldw, oldh: Integer);?
var?
  FormBounds: TRect;?
begin?
  FOwner.FWasFormRealignedFirstTime := True;?
  FOwner.FFormBounds.Width := w / PlatformAndroid.WindowService.Scale;?
  FOwner.FFormBounds.Height:= h / PlatformAndroid.WindowService.Scale;?
?
  FormBounds := FOwner.Bounds.Ceiling;?
  FOwner.Form.SetBoundsF(FormBounds.Left, FormBounds.Top, FormBounds.Width, FormBounds.Height);?
end;?
?
function TAndroidWindowHandle.TFormViewListener.onTouchEvent(event: JMotionEvent): Boolean;?

error: patch failed: Embarcadero/Athens/fmx/FMX.Platform.UI.Android.pas:1171
error: Embarcadero/Athens/fmx/FMX.Platform.UI.Android.pas: patch does not apply
Checking patch Embarcadero/Athens/fmx/FMX.Presentation.Android.Style.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Presentation.Win.Style.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Skia.Canvas.GL.pas...
error: while searching for:
type?
  { TGlSharedContextCustom }?
?
  TGlSharedContextCustom = class abstract(TGrSharedContext)?
  protected?
    FStencilBits: Integer;?
  public?
    property StencilBits: Integer read FStencilBits;?
  end;?
?
var?
  GlobalUseSkiaGLSwapInterval: Integer;?
?
implementation?
?
uses?

error: patch failed: Embarcadero/Athens/fmx/FMX.Skia.Canvas.GL.pas:28
error: Embarcadero/Athens/fmx/FMX.Skia.Canvas.GL.pas: patch does not apply
Checking patch Embarcadero/Athens/fmx/FMX.Skia.Canvas.Metal.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Skia.Canvas.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Skia.Canvas.Vulkan.pas...
Hunk #1 succeeded at 197 (offset -3 lines).
Hunk #2 succeeded at 285 (offset -3 lines).
Checking patch Embarcadero/Athens/fmx/FMX.StrokeBuilder.pas...
Checking patch Embarcadero/Athens/fmx/FMX.Types3D.pas...
Hunk #15 succeeded at 3200 (offset -3 lines).
Hunk #16 succeeded at 3285 (offset -3 lines).
Hunk #17 succeeded at 3320 (offset -3 lines).
Hunk #18 succeeded at 3521 (offset -3 lines).
Hunk #19 succeeded at 3758 (offset -3 lines).
Hunk #20 succeeded at 3808 (offset -3 lines).
Hunk #21 succeeded at 4617 (offset -3 lines).
Hunk #22 succeeded at 4808 (offset -3 lines).
Hunk #23 succeeded at 4817 (offset -3 lines).
Hunk #24 succeeded at 4930 (offset -3 lines).
Checking patch Embarcadero/Athens/fmx/FMX.VirtualKeyboard.Android.pas...
Checking patch Embarcadero/Athens/rtl/common/System.Skia.API.pas...
error: while searching for:
      procedure LINKLIB_cxx;                         external '/usr/lib/libc++.dylib';?
      procedure LINKLIB_cxxabi;                      external '/usr/lib/libc++abi.dylib';?
    {$ELSEIF DEFINED(ANDROID)}?
      procedure LINKLIB_EGL;                         external 'libEGL.so';?
      procedure LINKLIB_GLESv2;                      external 'libGLESv2.so';?
      procedure LINKLIB_log;                         external 'liblog.so';?
      procedure LINKLIB_cxxstatic;                   external 'libc++_static.a';?
      procedure LINKLIB_cxxabi;                      external 'libc++abi.a';?
    {$ENDIF}?
  {$ENDIF}?
{$ELSE}?

error: patch failed: Embarcadero/Athens/rtl/common/System.Skia.API.pas:2428
error: Embarcadero/Athens/rtl/common/System.Skia.API.pas: patch does not apply
Remove warnings from the copied files
The system cannot find the path specified.
Delphi source code has been copied and patched successfully
Press any key to continue .

--------------------

**Comment by Zeus64** [comment]
you need delphi athens 12.2

**Comment by ThePrefontaine** [comment]
Ah - that makes sense thanks. I have not yet gone up to 12.2 as last I checked it didn't support some (forget which) 3P stuff I use. Thanks again.
