### ISSUE TITLE
Multiple linebreaks ignored in TAlText if immediately before html tag

### ISSUE THREAD

**Issue by rj1102** [MagicFoundation/Alcinoe#54]
Just a minor issue while testing Rio:

  AlText1.TextIsHtml := True;
  AlText1.Text := 'paragraph'#13#10#13#10'<b>header</b>'; // CRLFs are ignored
  AlText1.Text := 'paragraph<b>'#13#10#13#10'header</b>'; // CRLFs are not ignored (OK)

Only occurs for multiple CRLFs, single CRLF works always okay.

**Comment by rj1102** [comment]
Just a minor issue while testing Rio:

  AlText1.TextIsHtml := True;
  AlText1.Text := 'paragraph'#13#10#13#10'&lt;b>header&lt;/b>'; // CRLFs are ignored
  AlText1.Text := 'paragraph&lt;b>'#13#10#13#10'header&lt;/b>'; // CRLFs are not ignored

Only occurs for multiple CRLFs, single CRLF works always okay.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
