### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by gbarroslimajr** [MagicFoundation/Alcinoe#62]
When inserting a MEMO-type component, and running on an Android 23 API device, it returns the error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader.Class.getClassLoader () on a null object reference'

**Comment by Zeus64** [comment]
Hi with version of delphi are you using? have you the same problem when running the ALFmxControl demo ?

**Comment by limelect** [comment]
was it fixed ?
same problem
https://github.com/Zeus64/alcinoe/issues/82

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
