### ISSUE TITLE
Not Compile

### ISSUE THREAD

**Issue by mirisu** [MagicFoundation/Alcinoe#63]
i am not complied alfmxcontrols,
[Exec Error] The command "D:\Rad Rio\alcinoe-master\tools\AddRJavaToClassesDex\AddRJavaToClassesDex.bat "D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source" "D:\Rad Rio\alcinoe-master\demos\ALFmxControls\Android\Debug\ALFmxControls.so" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\aapt.exe" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\platforms\android-28\android.jar" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" "C:\Program Files\Java\jdk1.8.0_60"&&D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source......\tools\AddRJavaToClassesDex\AddRJavaToClassesDex.bat "D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source" "" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\aapt.exe" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\platforms\android-28\android.jar" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" "C:\Program Files\Java\jdk1.8.0_60"&&D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source......\tools\AddRJavaToClassesDex\AddRJavaToClassesDex.bat "D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source" "D:\Rad Rio\alcinoe-master\demos\ALFmxControls\Android\Debug\ALFmxControls.so" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\aapt.exe" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\platforms\android-28\android.jar" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" "C:\Program Files\Java\jdk1.8.0_60"" exited with code 9009.

**Comment by Zeus64** [comment]
can you run the command D:\Rad Rio\alcinoe-master\tools\AddRJavaToClassesDex\AddRJavaToClassesDex.bat "D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source" "D:\Rad Rio\alcinoe-master\demos\ALFmxControls\Android\Debug\ALFmxControls.so" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\aapt.exe" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\platforms\android-28\android.jar" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" "C:\Program Files\Java\jdk1.8.0_60"&&D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source......\tools\AddRJavaToClassesDex\AddRJavaToClassesDex.bat "D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source" "" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\aapt.exe" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\platforms\android-28\android.jar" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" "C:\Program Files\Java\jdk1.8.0_60"&&D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source......\tools\AddRJavaToClassesDex\AddRJavaToClassesDex.bat "D:\Rad Rio\alcinoe-master\demos\ALFmxControls_source" "D:\Rad Rio\alcinoe-master\demos\ALFmxControls\Android\Debug\ALFmxControls.so" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\aapt.exe" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\platforms\android-28\android.jar" "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.3\dx.bat" "C:\Program Files\Java\jdk1.8.0_60"

inside a command prompt and say me with error you receive ?

**Comment by mirisu** [comment]
inside a command,building -> building event -> pre-build command.

**Comment by Zeus64** [comment]
no just in the command line (cmd.exe), copy paste the command (yes it's a command :) and say me the output

**Comment by bravesoftdz** [comment]
to solve the problem you should simply rename any file that are before the ALCinoe library in a single name or combine with underscore like this example here : 'Name1_Name2'
in my pc i have this path before: "D:\RIO Lib\ALCINOE" and i fix my problem by rename it as
"D:\RIO_Lib\ALCINOE"
   Generally the command prompt doesn't know the folders named with more one word and space between them ex: if i type inside CMD.exe this : cd.. D:\RIO Lib I WILL get an error said: the folder Rio doesn't exist....
hope my reply fix your problem....

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
