### ISSUE TITLE
Shadow in ATRectangle problem

### ISSUE THREAD

**Issue by Spelt** [MagicFoundation/Alcinoe#65]
Hi, 

First, thanks for the lib. Amazing work.

In IOS/Rio, I think there is an issue with the shadow when Fill.Kind is bitmap and wrapMode is TileStretch.  It does call the shadow routines but it does not paint the shadow. When Fill.Kind is Solid it just works.

Any idea?

**Comment by Zeus64** [comment]
I will need to look more closer at it, actually, Lib is built mostly for our own use and this use case was never tested by us. I will take a look at it

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
