### ISSUE TITLE
error in compile

### ISSUE THREAD

**Issue by megatkurniawan** [MagicFoundation/Alcinoe#71]
after a successful install, I tried to compile a sample on a demo. and having persistent errors, I followed the previous issue guide to copy the original file from embarcadero but the error persisted. I have copied 30 original files.

![image](https://user-images.githubusercontent.com/25611625/63082961-be835b00-bf71-11e9-9fc4-64126d259c03.png)

**Comment by bravesoftdz** [comment]
why you add this original files to the delphi library Path ?
look what i'm did to successful compile my MediaPlayer:
i add a custom Environement Variable from here:

[https://res.cloudinary.com/bravesofts/image/upload/v1565941425/Easy%20Delphi%202020/write_settings.png](here)

**Comment by megatkurniawan** [comment]
> 
> 
> why you add this original files to the delphi library Path ?
> look what i'm did to successful compile my MediaPlayer:
> i add a custom Environement Variable from here:
> [Environment Variable](https://res.cloudinary.com/bravesofts/image/upload/v1565941953/Easy%20Delphi%202020/Alcinoe_Environment_Variable.png)
> and add in my project search Path this:
> [search Path](https://res.cloudinary.com/bravesofts/image/upload/v1565941734/Easy%20Delphi%202020/Project_search_Path.png)
> this 👍
> $(ALCINOE)\references\embarcadero\rio\10_3_1\patched\fmx;$(ALCINOE)\references\embarcadero\rio\10_3_1\patched\rtl\ios;$(ALCINOE)\references\embarcadero\rio\10_3_1\patched\rtl\android;$(ALCINOE)\references\embarcadero\rio\10_3_1\patched\rtl\net
> 
> and finally for My project i need to add some java Libraries to My Project Library for TALVideoPlayerSurface.Video can Render and Play My Videos like Here:
> [Add Java Libraries](https://res.cloudinary.com/bravesofts/image/upload/v1565942204/Easy%20Delphi%202020/add_Java_Library.png)
> 
> i hope my Reply was Helpful for you ...

i follow from this issues https://github.com/Zeus64/alcinoe/issues/34

**Comment by megatkurniawan** [comment]
### 

> 
> 
> why you add this original files to the delphi library Path ?
> look what i'm did to successful compile my MediaPlayer:
> i add a custom Environement Variable from here:
> [Environment Variable](https://res.cloudinary.com/bravesofts/image/upload/v1565941953/Easy%20Delphi%202020/Alcinoe_Environment_Variable.png)
> and add in my project search Path this:
> [search Path](https://res.cloudinary.com/bravesofts/image/upload/v1565941734/Easy%20Delphi%202020/Project_search_Path.png)
> this 👍
> $(ALCINOE)\references\embarcadero\rio\10_3_1\patched\fmx;$(ALCINOE)\references\embarcadero\rio\10_3_1\patched\rtl\ios;$(ALCINOE)\references\embarcadero\rio\10_3_1\patched\rtl\android;$(ALCINOE)\references\embarcadero\rio\10_3_1\patched\rtl\net
> 
> and finally for My project i need to add some java Libraries to My Project Library for TALVideoPlayerSurface.Video can Render and Play My Videos like Here:
> [Add Java Libraries](https://res.cloudinary.com/bravesofts/image/upload/v1565942204/Easy%20Delphi%202020/add_Java_Library.png)
> 
> i hope my Reply was Helpful for you ...

if i follow you guide i found this error:

![image](https://user-images.githubusercontent.com/25611625/63155007-feaf1000-c03b-11e9-8bc4-631c6ea7254d.png)

**Comment by megatkurniawan** [comment]
> 
> 
> why you add this original files to the delphi library Path ?
> look what i'm did to successful compile my MediaPlayer:
> i add a custom Environement Variable from here:
> [Environment Variable](https://res.cloudinary.com/bravesofts/image/upload/v1565941953/Easy%20Delphi%202020/Alcinoe_Environment_Variable.png)
> and add in my project search Path this:
> [search Path](https://res.cloudinary.com/bravesofts/image/upload/v1565941734/Easy%20Delphi%202020/Project_search_Path.png)
> this 👍
> $(ALCINOE)\references\embarcadero\rio\10_3_1\patched\fmx;$(ALCINOE)\references\embarcadero\rio\10_3_1\patched\rtl\ios;$(ALCINOE)\references\embarcadero\rio\10_3_1\patched\rtl\android;$(ALCINOE)\references\embarcadero\rio\10_3_1\patched\rtl\net
> 
> and finally for My project i need to add some java Libraries to My Project Library for TALVideoPlayerSurface.Video can Render and Play My Videos like Here:
> [Add Java Libraries](https://res.cloudinary.com/bravesofts/image/upload/v1565942204/Easy%20Delphi%202020/add_Java_Library.png)
> 
> i hope my Reply was Helpful for you ...

if i follow you guide i found this error, this is iam compile you source media player
![image](https://user-images.githubusercontent.com/25611625/63155216-577ea880-c03c-11e9-8e69-188e55f67178.png)

**Comment by bravesoftdz** [comment]
look for android devices you don't need to add the file originals inside the search path
in my project media player i use just this :
![Search Path android](https://user-images.githubusercontent.com/16312458/63175055-83e9f300-c043-11e9-8b13-4faf284fa200.png)

**Comment by viniciusfbb** [comment]
## Using the Alcinoe without install

**1**) Download the Alcinoe, create a new folder in your project folder, named "third-party" and save the alcinoe there.

**2**) Open: Project > Options > Building > Delphi Compiler > 

**3**) Select Target "All configurations - All platforms"

**4**) Add this to the search path: 

`third-party\alcinoe\references\embarcadero\rio\10_3_2\patched\rtl\android;third-party\alcinoe\references\embarcadero\rio\10_3_2\patched\rtl\ios;third-party\alcinoe\references\embarcadero\rio\10_3_2\patched\fmx;third-party\alcinoe\references\embarcadero\rio\10_3_2\patched\rtl\net;third-party\alcinoe\source;$(BDS)\source\rtl\common;$(BDS)\source\rtl\net;$(BDS)\source\fmx`

- In this case, I consider that the alcinoe folder that you have is in third-party folder inside your project folder.
- Note: The path order is relevant!

**5**) Save

**6**) In the project folder, delete the output directory of the units (dcu, .o, .a, ...), to make sure we recompile everything again

**7**) Build your project and Run

**Comment by bravesoftdz** [comment]
remark 👍
some components doesn't require to add the search path to your app for example :
**TALVideoPlayerSurface** alone inside your project can compile and work without adding
the search path for both patched and originals.
look at video here:
[tutorial](https://www.facebook.com/100027867783790/videos/356320815306842/)

and if you add for example **TALLayout** to your form or project will doesn't compile untill you will 
add the search path for both: **patched** & **originals**

i have no problem before , i mean i was using just the **patched** files and i compile and work Excelent but when try to reinstall my delphi and begin to test in second time i face the problem saying **FMX.Types3D.pas** is compiled with another version ... So i add just the **originals** to my project search path and is compile and work with success?
Anyway i don't know the reason why my first installation of delphi doesn't tell me the error above ...

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
