### ISSUE TITLE
Patched units and precompiled units (FireDAC)

### ISSUE THREAD

**Issue by ChrisNineNineEight** [MagicFoundation/Alcinoe#75]
Hi,

we've tried getting Alcinoe to work in 10.3.1 and have already added the folder with the original fmx source files to the search patch, but it seems like we have an (to us) unsolvable error here:

[dcc32 Fataler Fehler] Form1.pas(21): F2051 Unit FireDAC.FMXUI.Wait wurde mit einer unterschiedlichen Version von FMX.Forms.Application compiliert

The unit FireDAC.FMXUI.Wait seems to be precompiled as we can't find it anywhere in the Delphi sources.

Any ideas on how to solve this?

And if I may ask: Why do we need to add all those source files anyway? Why is it necessary to patch all those files?

**Comment by Zeus64** [comment]
hi, FireDAC.FMXUI.Wait.pas is in C:\Program Files (x86)\Embarcadero\Studio\20.0\source\data\firedac\FireDAC.FMXUI.Wait.pas

We need to source because I was force to patch some original source file of delphi, for example to be able to draw OES texture (a texture that comes from video player for example) or to draw a fluid animation (60fps) when you scroll a scrollbox.

**Comment by ChrisNineNineEight** [comment]
This is the problem then. We've got these three in C:\Program Files (x86)\Embarcadero\Studio\20.0\source\data\firedac\:

FireDAC.Phys.pas
FireDAC.Phys.SQLGenerator.pas
FireDAC.Phys.SQLPreprocessor.pas

Is it possible that you've got the Enterprise or Architect edition of Delphi? Because neither the Professional nor the Community edition of Delphi 10.3.1 (and 10.3.2) have more than those three files for FireDAC.

**Comment by pasiek22** [comment]
@ChrisNineNineEight Were you able to solve this problem?. I have 10.3.3 and also I only have these 3 files.

**Comment by ChrisNineNineEight** [comment]
@pasiek22 of course not. He just marked this problem as "closed" because he has the Enterprise or Achitect edition. The Community and Professional editions don't have those files.

@Zeus64 this is still a problem. What edition of Delphi do you have? Because the needed files don't exist in the Community and Professional editions...

**Comment by Zeus64** [comment]
@pasiek22 if you have the professional, then you must have the source code of the rtl ? I think even the community have the source code. What delphi version do you have ?

**Comment by pasiek22** [comment]
I have professional version (10.3.3).  
And I have the same problem with TChar components. I don't have source files in my version.

**Comment by ChrisNineNineEight** [comment]
Version:
Currently it's Delphi 10.3.3 Professional.

As I said:
We've got these three in C:\Program Files (x86)\Embarcadero\Studio\20.0\source\data\firedac:

FireDAC.Phys.pas
FireDAC.Phys.SQLGenerator.pas
FireDAC.Phys.SQLPreprocessor.pas

And there are no firedac files in C:\Program Files (x86)\Embarcadero\Studio\20.0\source\rtl

Everything about FireDAC is precompiled in the community and professional editions.

But apart from that we do have other precompiled libraries like UniDac from Devart without source and those would need the original FMX.Forms.Application too. So that would create problems too.

**Comment by Zeus64** [comment]
@ChrisNineNineEight , @pasiek22 Ok I see this is bad :( I was not aware about this. I will try to see if it's possible to implement an option where the patching of the rtl is not absolutely necessary ...

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
