### ISSUE TITLE
Exoplayer issues

### ISSUE THREAD

**Issue by TetrisSQC** [MagicFoundation/Alcinoe#76]
Hi,

i do have some issues which are probably not directly caused by the implementation, but maybe you have an idea? I placed the surface with align contents on the screen and play a video. The video is for a while always just on 1/4 of the screen before it updates to the display.
Some android devices are also unable to play mp4 (h264, aac) files which work fine on others devices. Same with audio streams like: http://c11.prod.playlists.ihrhls.com/1477/playlist.m3u8.
Is there a chance to figure out why this happens?

Christian

**Comment by TetrisSQC** [comment]
I should probably be more specific. I'm unable to play UDP protocols like udp://@224.10.10.1:5000. According to the log exoplayer complains that the protocol is unknown.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
