### ISSUE TITLE
Please contact me!

### ISSUE THREAD

**Issue by delphiprofi** [MagicFoundation/Alcinoe#80]
Hi Zeus!
I'm like your FMX stuff. Perhaps you know me:
https://delphiprofi.blogspot.com/
http://www.delphiprofi.de

It would be great if you find the time to contact me: 
- Skype  Mavarik66
- Mail Frank@delphiprofi.de

Thanx Frank

**Comment by checkdigits** [comment]
Hey Frank - I've messaged you on the MVP Slack system - IanB.

**Comment by Zeus64** [comment]
Hey Franck, we are already in contact on MVP slack ;) I close this issue for now
