### ISSUE TITLE
Is Seattle incompatible ??

### ISSUE THREAD

**Issue by joaomarcosreal** [MagicFoundation/Alcinoe#84]
Hello Guys!
There isn't a package for Delphi Seattle ?
It runs just for versions after Delphi Rio ?

**Comment by limelect** [comment]
You can try to compile the dpk . It has almost nothing 
to do with the Delphi version EXCEPT
the name ..250.bpl  ..240.bpl  and the requires.
Usually once you load the project dpk delete
the requires's that are associated with the project
and they will be "picked up" during compilation.
As for the BPL name change to what it suit YOU. 
If the source compiles in your Delphi version you are
lucky. Other wise you have to change the source.

**Comment by joaomarcosreal** [comment]
Thank you man!!
I'll try these steps.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version. Seattle is not anymore supported
