### ISSUE TITLE
TAlRectangle not fill with any color en Delphi 10.3 update 3

### ISSUE THREAD

**Issue by proyectoanamnesis** [MagicFoundation/Alcinoe#95]
Hello. greetings from Argentina.

I use Delphi 10.3.3 Version 26.0.36039.7899 

I put into form a TAlRectangle controls and fill with solid color, but are not filled with any color.

I use google translate. Sorry for my bad English

**Comment by Zeus64** [comment]
hi, no problem with you english :) can you put here the sample project you made with the TALRectangle ?

**Comment by proyectoanamnesis** [comment]
Something is wrong in my development pc. 
TRectangle control works fine now. I'm sorry

**Comment by proyectoanamnesis** [comment]
Today I can see that TAlrectangle and TAlcircle not work with Gradient fill, but fill solid color work ok.

to test:

I Create an blank project and put into form one TAlrectangle control then change fill to Gradient, when i try run into device I can see not fill anything, but I change again to solid color this work ok.

**Comment by Zeus64** [comment]
Hello, everything has been fixed in the latest committed version.
